### ISSUE TITLE
SoS notebook no longer shows bash output

### ISSUE THREAD

**Issue by gaow** [vatlab/sos-notebook#102]
On the SoS live server I tried to run `WP2018_Process_Oriented.ipynb`. I get:

![2018-08-01-23-21-32_scrot](https://user-images.githubusercontent.com/917985/43562352-aad47324-95e1-11e8-83ba-1e94af33e0d9.png)

It indeed works as shown in the `preview`. But the first cell now has no output. This behavior is not expected.

**Comment by BoPeng** [comment]
Did you try it locally?

**Comment by gaow** [comment]
I have not tried locally yet. A bit hectic on my end since I had to move the server computer out of the computer room temporarily due to renovation. That is why I restarted (thus also updated) the live server, and ran into this problem when I tested to ensure things work. 

There will be a power outage again tmr 8am - 11am for the renovation. I'm going to shut down the server tmr early morning. Will try it locally later -- need to head home now.

**Comment by BoPeng** [comment]
OK, I can reproduce the problem locally. Let me check.

**Comment by BoPeng** [comment]
The scripts do not produce anything, so unless you run `%sosrun ` with `-v2`, nothing will be displayed.

The empty stderr/stdout lines need further investigation though.

**Comment by BoPeng** [comment]
It is arguable what need to be displayed by default and what not. Current implementation tried not to use different verbosity level in SoS (e.g. use `env.logger` in `run` mode and `env.debug` in `interactive` mode) but set the default level to `-v1` for interactive mode to avoid a summary of workflow at the end of each small workflow.

**Comment by gaow** [comment]
I think I get your point, but still with `-v1` isn't it true that we should see some progress bar? Currently nothing is displayed, which looks a bit awkward. I can add `-v2` to all our examples (not those already in zenodo), but it is also awkward ...

**Comment by BoPeng** [comment]
I think the best solution is to make the output consistent between batch and interactive mode. My problem was that the batch mode has more output than I would like to see in a notebook environment which makes the notebook larger and difficult to navigate. I can see two solutions:

1. Use the new 'hint' message type for essential messages. This is not yet an official sos logging type but has been used to generate output that shows in console as 'HINT:' and as hint message (gray text etc) in notebook.

2. Reduce some of the current `info` output  to `debug`. The biggest one would be the summary line, which is line and shows with every workflow.

**Comment by gaow** [comment]
I do not think i have seen the "hint" type before ... I think 2 is good idea. Or, is there a way to send those messages to the side panel?

**Comment by BoPeng** [comment]
I think the side panel is a better solution although a bit difficult to implement. Let me check.

**Comment by BoPeng** [comment]
This naturally fits into a workflow or sos panel of https://github.com/jupyterlab/jupyterlab/pull/4879

**Comment by gaow** [comment]
Okay, but do we have a temporary solution to this, or should I just add `-v2`? Otherwise it might look bad when users try to reproduce the examples of the SoS workflow paper.

**Comment by BoPeng** [comment]
Try the `logging` branch and let me know if it works for you. I will also need to change default logging level to `INFO` for interactive mode, but you can use `-v2` to test.

**Comment by gaow** [comment]
This behavior is good! I'll update the live server after a new release is made.

**Comment by BoPeng** [comment]
I will release after #23 is fixed (or proven to be difficult to fix).

**Comment by BoPeng** [comment]
I have released sos 0.9.16.2 and sos notebook 0.9.16.1, you can update the docker image with them.

**Comment by gaow** [comment]
Unfortunately something else is wrong:

![2018-08-03-08-48-44_scrot](https://user-images.githubusercontent.com/917985/43646275-15d4faf4-96fa-11e8-9c3e-6edc19342536.png)

**Comment by BoPeng** [comment]
For #23, the `input` function is aliased to a Jupyter function to get input from the Jupyter frontend, this for whatever reason affects the handling of `input=` parameter here.

**Comment by BoPeng** [comment]
The key problem here is to separate type trait

```
var: type = 1
```
with
```
pandoc: input=1
```
We excluded `input` as builtin function but it is no longer a builtin function in Jupyter.

**Comment by BoPeng** [comment]
OK. Update to 0.9.16.3 and let me know if there is any other problem. I will make a new sos notebook release to depends on this version after your confirmation.

**Comment by gaow** [comment]
Great! Now examples work. The live server is also up to date.

**Comment by BoPeng** [comment]
OK, I will make a new release of sos notebook.
