### ISSUE TITLE
Workflow cell run warning

### ISSUE THREAD

**Issue by gaow** [vatlab/sos-notebook#106]
See these 3 cells below:

![2018-08-08-17-00-00_scrot](https://user-images.githubusercontent.com/917985/43866786-a153ec3a-9b2c-11e8-8893-c44421d5f193.png)

Cell 3 is good. Cell 2 the warning message is wrong right? Because i do have used `%sosrun`.

For Cell 1, yes the warning message makes sense. But it just does not look very nice when I click on `restart and run all` to run the entire notebook. Truthfully I do not think we need that prompt but i do not have a strong opinion on it.

**Comment by BoPeng** [comment]
ok. The message was added because now it would be usually displayed at the side panel. Removed anyway because it is difficult to detect if the workflow is triggered by `%sosrun`.
