### ISSUE TITLE
%run execute [global] sections outside of a cell

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos-notebook#113]
The reason for vatlab/sos#1026 was found. Basically, there are several `[global]` sections in the notebook, which interferes with the processing of the global section in the example. (Basically, there are direct assignment of `excel_file = 'filename'` and `excel_file` is assigned to a string so parameter is not processed when it is already in the namespace.

I think this behavior is not clean at all and should be changed. I mean, it is much easier just to state that `%run` executes workflow defined in the present cell, and `%sosrun` executes workflow defined in the entire notebook. It is confusing to have `%run` reaches out of the cell but only gets `[default]` sections.

**Comment by BoPeng** [comment]
@gaow I believe we have had this back and forth a few times. `%run` works strictly within a cell once and broke some of your scripts and we restored.

**Comment by gaow** [comment]
> %run works strictly within a cell once

As far as I can recall, I was expecting that `%run` be confined to cell yet is able to use `global` settings. Otherwise it seems inconvenient. Was this behavior causing issues?

**Comment by BoPeng** [comment]
Yes, the example notebook has a few `[global]` sections and `excel_file` was assigned a value before `parameter: excel_file` is processed as a parameter.

The reason we do not process `parameter: excel_file` if it already exists is complicated, related to performance and the use of parameter in nested workflows when parameters are passed directly from master workflow, not from command line.

**Comment by BoPeng** [comment]
I mean, if we do want to restrict workflow to a cell but use all global sections, we can always do

```
%sosrun this_particular_cell
[this_particular_cell]
```
right?

**Comment by gaow** [comment]
Right, I dont think I can find a counter example now. So maybe let's revert to the old behavior and I can change my notebook accordingly?

**Comment by BoPeng** [comment]
ok. I will do it.
