### ISSUE TITLE
`%revisions` add an option to only show tagged results

### ISSUE THREAD

**Issue by gaow** [vatlab/sos-notebook#114]
First I want to say that `revisions` feature is kind of a game changer for me. I stopped saving my earlier version of anlaysis by date, because now it is so much earsier to retrieve them!

But perhaps it is better to have more control over it. Currently it shows everything up to `-n` backward in time. sometimes I make lots of cosmetic changes they end up showing in the revision table. It is not very good. For a research project we do not have releases but I find maybe `tag` is a good thing to do. For example I explore some parameters under certain assumption eg "non-sparse polygenic effects version" that I later decide to abandon. I can add a tag for it `git tag -a v1.0 -m "this V1 model is no good"` . And we can have `%revisions` to show only tagged versions? Or, only tagged version greater than / smaller than ...? This may also encourage user's good practice to use tags (if it is indeed a good practice).

**Comment by BoPeng** [comment]
`%revisions` accepts whatever parameters acceptable to the underlying `git log` command accepts (`-n` is only one of the easiest ones). So you can explore the possibilities there.

**Comment by gaow** [comment]
Indeed! The parameter is:

```
git log --tags --no-walk
```
