### ISSUE TITLE
Ability to write custom magics

### ISSUE THREAD

**Issue by kirang20** [vatlab/sos-notebook#131]
Does SOS Notebook have support for writing custom magics? Looking at the code it seems like magics are being loaded from `SoS_Magics` and the list of magics seems static. We have few use cases for which would like to write custom SOS magics, so any help in this regard is much appreciated. 

Thank you.

**Comment by BoPeng** [comment]
Could you elaborate what these magics would do? If these are for any subkernel, you can define them in subkernels and SoS would call them as subkernel magics. Otherwise we can implement a loadext magic to load these magics but then the question is what APIs you need to control the internal of SoS.

**Comment by kirang20** [comment]
Thanks for the response. Let me provide some details about the custom magic.

We have functions (Python, R, etc) which will be loaded and made available in the notebook for the user to run. These functions operate on data and this data needs to be prepared before it is passed into these functions. We would like to provide a custom magic which will help users prepare data and make it easier to invoke these functions. The custom magic will take arguments which are specific our domain. Below is an example of how the magic would be used:
```
%%custom_magic --language Python --param1 value1 --param2 value2
python_function1()

%%custom_magic --language R --param1 value1 --param2 value2
R_function1()
```

Is there any way to do this currently?

**Comment by BoPeng** [comment]
Are `%%custom_magic` written in Python? My question here is that `custom_magic` can well be regular python (or R, or other) functions and be called in the same (if using the same language) or a different (if using a different language) cell, so no "magic" is actually needed. Actually, when I had a similar need, I would just write a short workflow (in SoS) and use `%sosrun prepare_data --options` to prepare the data, so perhaps `%sosrun` is what you need?
