### ISSUE TITLE
%preview on HTML file messup notebook layout

### ISSUE THREAD

**Issue by gaow** [vatlab/sos-notebook#140]
To reproduce:

1. Go to https://vatlab.github.io/sos/live
2. Open up examples -> WP_2018_SoS_Manuscript -> Process_Oriented.ipynb
3. At the end of the page run `%sosrun`
4. run `%preview report.html` (with or without `-n`).

The result looks bad. But it does work fine in my JupyterLab IDE. This is why I did not discover it earlier.

**Comment by BoPeng** [comment]
ok. this is because the css from html is considered as master css. This is an known issue.

**Comment by gaow** [comment]
From @BoPeng 

> What template did you use? There is a weird css that limits the page
size to 42em.

This should explain also #139 ! 

Let me fix that CSS file ...
