### ISSUE TITLE
Change the side panel to a console window.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos-notebook#150]
With long discussions on the JupyterLab side, it is becoming clear that the side panel and related features will be implemented in JLab console window. That is to say, the console window
1. will be destination of line by line execution (the runInConsole feature)
2. will be used to display `transient_display_data` (the `transient_message` plugin)

It is hard to say which interface is better but the console window has the advantage of saving all histories, which will fix #143 because the output of the preview magic will not overwrite the error message from previous statement.

**Comment by BoPeng** [comment]
Work in progress:

![image](https://user-images.githubusercontent.com/9889312/49492998-02896200-f820-11e8-98a5-a5cb04ded0d0.png)

**Comment by BoPeng** [comment]
@gaow @HenryLeongStat 

Still need to fix execution counter and perhaps other stuff, but let me know how you think of this new side panel. It resembles the console window of JupyterLab.

**Comment by HenryLeongStat** [comment]
Liking it on my end!!

When I expand the cell, the color and the little triangle don't expand when the size of the cell reaches to a certain size.

<img width="313" alt="screen shot 2018-12-06 at 10 36 09 am" src="https://user-images.githubusercontent.com/26916551/49597765-c3076680-f942-11e8-99b2-14ab36158b7f.png">

**Comment by BoPeng** [comment]
Cannot reproduce. There is a maximum of 1/2 width of the side panel but I do not see the triangle goes into the middle. I am still tweaking, perhaps you are not at the latest trunk? Note that you need to do `python -m sos_notebook.install` restart the browser after `pip install . -U`.

![image](https://user-images.githubusercontent.com/9889312/49599832-81c58580-f947-11e8-905c-292b1d65182e.png)

**Comment by HenryLeongStat** [comment]
The problem begins to show up when you have some history above and the scrollbar shows up:

<img width="317" alt="screen shot 2018-12-06 at 11 13 54 am" src="https://user-images.githubusercontent.com/26916551/49600147-23e56d80-f948-11e8-8c91-32de5c93bff3.png">
<img width="310" alt="screen shot 2018-12-06 at 11 13 41 am" src="https://user-images.githubusercontent.com/26916551/49600148-23e56d80-f948-11e8-8fa1-20ada6101d13.png">

**Comment by gaow** [comment]
@BoPeng I'm mostly on JupyterLab these days for SoS Notebook. Maybe missing some of the nice new developments here. But when i was just trying to reproduce @HenryLeongStat 's issue I noticed the side-panel can be dragged out of the embedded page and become floating again and cannot be easily restored. ...

**Comment by BoPeng** [comment]
I disabled dragging yesterday, how did you drag?

**Comment by HenryLeongStat** [comment]
Interesting... I can't drag the side panel.

**Comment by BoPeng** [comment]
@gaow I believe that you forgot to do `python -m sos_notebook.install` because the screenshot is not the master.

**Comment by BoPeng** [comment]
I can now reproduce the middle triangle thing.

**Comment by BoPeng** [comment]
I think I will just remove the triangle because it is not usable.

**Comment by gaow** [comment]
I have a local Makefile that always does `python -m sos_notebook.install`. Let me see what is going on here ...

**Comment by HenryLeongStat** [comment]
Exactly! Expanding the side panel doesn't need the triangle. For the color along with the code cell, it still looks good even it doesn't expand along with the code cell. 

But for the history above, maybe better to change the color of the background of the code? 

<img width="311" alt="screen shot 2018-12-06 at 11 55 53 am" src="https://user-images.githubusercontent.com/26916551/49602375-ea176580-f94d-11e8-8841-119969442504.png">

**Comment by BoPeng** [comment]
OK. Input background is restored, but the output zigzag (https://github.com/vatlab/sos-notebook/issues/153) remains. Checking if there is anyway to fix it.

**Comment by HenryLeongStat** [comment]
Looking good!!
<img width="309" alt="screen shot 2018-12-06 at 3 35 06 pm" src="https://user-images.githubusercontent.com/26916551/49613166-8d777300-f96c-11e8-88fa-188436bd69fe.png">

**Comment by HenryLeongStat** [comment]
How about making the color of the "In [1]" rectangle small?

**Comment by BoPeng** [comment]
What do you mean?

**Comment by HenryLeongStat** [comment]
For example, the zigzag below is like 

<img width="263" alt="screen shot 2018-12-06 at 3 41 30 pm" src="https://user-images.githubusercontent.com/26916551/49613543-6ff6d900-f96d-11e8-8dce-4c2f9dbd67e7.png">

<img width="187" alt="screen shot 2018-12-06 at 3 43 29 pm" src="https://user-images.githubusercontent.com/26916551/49613658-bb10ec00-f96d-11e8-8055-2298988509f3.png">

Is there a way to make the blue rectangle smaller? Or, changing yellow to transplant?

**Comment by BoPeng** [comment]
I have tried... The problem seems to be the because the output prompt was always clear, they did not bother to make input and output prompt exactly the same size. Instead, the output prompt was made a bit wider to indent the output.

**Comment by HenryLeongStat** [comment]
I see... And I see the reason why you changed the color of the background of the code in history of the side panel into the same color as the "blue" rectangle.
