### ISSUE TITLE
Replace rerun with %save + %runscript or %runfile

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos-notebook#179]
Although `%rerun` is convenient in rerunning the same workflow with different options, it is not clear what is the "previous run'. Since we already have the `%save` magic to save the content of cell to a file, it seems to make sense to introduce `%runfile` to workflow from an external script. It is similar to `!sos run script` but can make use of the task status, background mode etc.

**Comment by gaow** [comment]
does it support running `ipynb` format?

**Comment by BoPeng** [comment]
But having `a` for `a.sos` or `a.ipynb` makes the `%runfile filename` suspicious so I am thinking if I should rename the magic to something like `%runscript`, which does not sound quite correct either. Perhaps I should require the specification of filename.

**Comment by BoPeng** [comment]
OK. I guess I will just keep the extension search feature hidden...
