### ISSUE TITLE
Testing sos notebook frontend

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos-notebook#185]
This ticket is created to track the progress of front-end testing.

* [x] Appearance of language selection dropdown.
* [x] Check cell language by selecting language from dropdown
* [x] Change color of input prompt
* [x] Change color of output prompt
* [x] New code cell use language of previous code cell
* [x] New code cell use language of previous code cell, even after markdown cell

More later.

**Comment by BoPeng** [comment]
@jma7 I have moved your dockerfile etc to development, please write a shell script to build docker image and push to mdabioinfo because I do not know the tags for the dockerfile. You also have a Docker-file_old, which I do not know if should be removed.

**Comment by jma7** [comment]
I don't have the permission to push image to ```mdabioinfo```.
On your machine, you could do
```
  docker pull junmahouston/notebook_test:latest
  docker pull junmahouston/eg_sshd:latest
  docker tag 967c99ae1dd0  mdabioinfo/sos_notebook_test:latest
  docker tag d017d220c284  mdabioinfo/eg_sshd:latest
  docker push mdabioinfo/sos_notebook_test:latest
  docker push mdabioinfo/eg_sshd:latest
```
Then, I will go from there.

**Comment by BoPeng** [comment]
ok, done with all the commands.

**Comment by jma7** [comment]
I have made the change to make docker containers working on Travis. There is an error in ```TestSoSMagics.testMagicRevisions```, other tests are passed. 
https://travis-ci.org/vatlab/sos-notebook/builds/515310993

**Comment by BoPeng** [comment]
The test failed because your docker environment does not have `git` command. Let me comment out this test for now. We can add `git` to the image later.

**Comment by jma7** [comment]
It seems ```git``` is installed in the container.

**Comment by BoPeng** [comment]
Yes, I realized that so I disabled the entire test (not just test for `git`). I can have a look at it later after the framework passes.

**Comment by BoPeng** [comment]
For whatever reason 

```
@unittest.skipIf('TRAVIS' in os.environ, 'skip in travis.')
```
does not work... can be a problem with version of `pytest`.

Comment out the entire test for now.

**Comment by BoPeng** [comment]
A selenium test still fails

**Comment by jma7** [comment]
All passed now.

**Comment by jma7** [comment]
Since we don't build the container every time, the sos in the containers are not the latest version. Does ```pip install sos``` always get the latest version?

**Comment by BoPeng** [comment]
If you have an existing version, you will need to use `pip install sos -U`. Anyway, I am glad that the tests work and I will figure out how to add more tests later.
