### ISSUE TITLE
f-string syntax highlight

### ISSUE THREAD

**Issue by gaow** [vatlab/sos-notebook#19]
This in fact has been bothering me for a while now:

![2017-11-27-19-17-45_scrot](https://user-images.githubusercontent.com/917985/33297656-e56fb086-d3a7-11e7-85f4-6d2f57e71a8d.png)

Basically any text after an f-string syntax will be highlighted in red as raw string in the SoS notebook cell (python sub-kernel). Do you observe the same? A pure Python notebook would not have this issue.

**Comment by BoPeng** [comment]
We should be able to fix it if pure Python does not have this issue. I will have a look.

**Comment by BoPeng** [comment]
In theory we will also need to highlight things between braces but I will wait for the Python kernel to do it (before I can copy).
