### ISSUE TITLE
%run magic error

### ISSUE THREAD

**Issue by jma7** [vatlab/sos-notebook#195]
I can't replicate the %run magic from the documentation on the server.
![screen shot 2019-02-25 at 11 31 54 am](https://user-images.githubusercontent.com/22623882/53356446-0bef0b80-38f1-11e9-9ef5-c026565887fb.png)

**Comment by BoPeng** [comment]
Yes, `%run` magic has changed to be completely detached, that is to say the execution will not affect anything in the notebook (while here we pass the variable to the underlying `sos` command as command line option.

Please update the doc and help message of `%run` if needed.

**Comment by jma7** [comment]
What should be the behavior of ```%rerun```? I got error message as well.

**Comment by BoPeng** [comment]
`%rerun` was replaced by [`%runfile`](https://vatlab.github.io/sos-docs/doc/user_guide/sos_in_notebook.html#-Execute-external-script-with-magic-runfile) . https://github.com/vatlab/sos-notebook/issues/179 has the reason.

**Comment by jma7** [comment]
So now the operation is like:
```
%run
%save check -f
parameter: a = 10
[10]
print(f"a is set to f{a}")
```
```
%runfile check --a 20
```
The help doesn't mention that variable value could still be passed in, but it is still working.

**Comment by BoPeng** [comment]
Yes, `%runfile` is almost identical to `sos run` from command line so any parameter can be passed. Please update the doc if needed.
