### ISSUE TITLE
Selenium tests fail after separating magics

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos-notebook#210]
After I separate the `test_magics` test into tests for each magic (eg. [here](https://github.com/vatlab/sos-notebook/blob/master/test/selenium/test_magics.py#L52), each individual test passes but overall only the first test passes, and all others fail with a time out error. It seems that each test needs to conclude in some way.

**Comment by BoPeng** [comment]
@jma7 Please have a look.

**Comment by BoPeng** [comment]
Also, I do not understand why [this test](https://github.com/vatlab/sos-notebook/blob/master/test/selenium/test_magics.py#L68) passes, but fails if I change

```
command = "sosa = '24'"
```
to
```
command = "sosa = f'{24}'"
```

I doubt that is something wrong with Python3 kernel, but the command works fine outside of selenium.

**Comment by BoPeng** [comment]
The error message for the first cell is

```
 line 1\n    sosa = f\'{24}\' \'\n                    ^\nSyntaxError: EOL while scanning string literal'
E        +  where 'File "<ipython-input-1-a279d06a4059>", line 1\n    sosa = f\'{24}\' \'\n   
```

so for whatever reason an extra quote was added to `command`.

**Comment by BoPeng** [comment]
The split version is moved to `split_test` branch, but the master still fails after merging the tests. 

I think it is important to first figure out why
```
sosa = f'{24}' 
```
fails to execute in Python 3 kernel.

**Comment by jma7** [comment]
Just want to let you know that in conftest.py, if you change 
```
elif os.environ.get('JUPYTER_TEST_BROWSER') == 'chrome':
        #driver = Chrome()
        chrome_options = webdriver.ChromeOptions()
        chrome_options.add_argument('--no-sandbox')
        chrome_options.add_argument('--window-size=1420,1080')
        chrome_options.add_argument('--headless')
        chrome_options.add_argument('--disable-gpu')
        driver = Chrome(options=chrome_options)
```
to 
```
elif os.environ.get('JUPYTER_TEST_BROWSER') == 'chrome':
        driver = Chrome()
```
You could see the actions in real browser to get some ideas of what went wrong. 

In test_magic_expand, an extra curly brace was inserted at the end, I have to remove the right curly brace in the content to get the correct expression, don't know why.  
```
idx = notebook.append_and_execute_cell_in_kernel(content=dedent("""\
            %expand ${ }
            if (${par} > 50) {
                cat('A parameter ${par} greater than 50 is specified.');
            """), kernel="R")
```
In test_magic_preview
```
command="%preview -n a \na = [1, 2, 3] "
```
This line gives error.

**Comment by BoPeng** [comment]
Good suggestion! The extra brace thing might also explain why `a = f'{24}'` becomes `a=f'{24}' '`.

**Comment by jma7** [comment]
I tried
```
sosa = f'{3*8}'''
```
The f string got executed without error, so you might use this as a temporary fix. I still don't know what causes the extra quote. I tried to send ```sosa=f'{24}'``` to original notebook cell, the extra quote was still added. So I suspect the problem is in selenium.

**Comment by BoPeng** [comment]
If you get execute JS code, you can use something like `IPython.notebook.get_cell(idx).set_text()` to set text to cell directly...

**Comment by jma7** [comment]
```
self.browser.execute_script("IPython.notebook.get_cell("+str(index)+").set_text("+repr(content)+")")
```
This seems working.

**Comment by BoPeng** [comment]
Good. Let me test.

**Comment by BoPeng** [comment]
Great. It seems to be working all right. Thanks!
