### ISSUE TITLE
Running python3 and R processes spawned by sos and not terminated after usage

### ISSUE THREAD

**Issue by MatteoSchiavinato** [vatlab/sos-notebook#228]
I have been using sos-notebook for a while now, and I have noticed this behavior relatively often. I run sos with R, bash and python3 kernels, usually all present in all my notebooks.

Whenever an issue comes out with a python3 or an R kernel, which forces me to restart the Notebook kernels, a new python3 / R instance is generated but the old one does not get killed. If I repeat the process 2-3 times, I end up with 2-3 python3 or R processes that are not actually used.

Is this issue known (and fixed already)? Could by any chance be an issue of our OS?

**Comment by BoPeng** [comment]
Thanks for your report. There are a few possible scenarios:

1. If you use the `restart kernel` from the Jupyter interface, the `SoS` kernel will be killed and restarted. I am not quite sure what will happen to the subkernels because they are subprocesses of the SoS kernel and should in theory also be killed. 

2. `%shutdown -r` should kill subkernels and restart SoS.

3. `%shutdown R -r` is supposed to reboot `R` (or other subkernel) without affecting other kernels.

The behavior might be OS-dependent. What is your OS? I know that R kernels do not shutdown cleanly under windows ([vatlab/sos-r#8](https://github.com/vatlab/sos-r/issues/8)) and we currently do not have a solution for it.

**Comment by MatteoSchiavinato** [comment]
> The behavior might be OS-dependent. What is your OS? I know that R kernels do not shutdown cleanly under windows ([vatlab/sos-r#8](https://github.com/vatlab/sos-r/issues/8)) and we currently do not have a solution for it.

CentOS 6.7.

**Comment by MatteoSchiavinato** [comment]
>     3. `%shutdown R -r` is supposed to reboot `R` (or other subkernel) without affecting other kernels.
I just tried with both python3 and R:

1. with python3 it says that it is not running
2. with R it doesn't say anything, completes the cell task with no output, but the 3 R processes are still there.

**Comment by BoPeng** [comment]
ok, under linux (Ubuntu)

1. start `jupyter notebook`, 1 process, `python .../jupyter-notebook`
2. start sos notebook, 2 processes, with `python -m sos_notebook.kernel`
3. restart sos kernel, 2 processes, with a different sos kernel.
4. start bash kernel with a command, 3 processes `python -m bash_kernel`.
5. Kernel -> restart kernel, the bash kernel process is gone.
6. `%shutdown Bash -r` restarts the bash kernel (a new process ID).

**Comment by BoPeng** [comment]
> with python3 it says that it is not running

You need to use `Python3` or it is possible that the kernel has not started if you have not really used Python3 to evaluate a cell.

> with R it doesn't say anything, completes the cell task with no output, but the 3 R processes are still there.

If you have 3 R processes, they might be the zombies from this bug. But one of them should have a new process ID.

**Comment by MatteoSchiavinato** [comment]
I just managed to get the three of them together in a `top` window, and they look like this (<username> would be my user and the first column is the PID):

25370   /software/<username>/python3 -m sos_notebook.kernel -f /home/<username>/.local/share/jupyter/runtime/kernel-c2e7c781-0011-4952-994f-f71e5c5d4f2f.json
25371   /software/<username>/python3 -m sos_notebook.kernel -f /home/<username>/.local/share/jupyter/runtime/kernel-8eed2272-1735-4cf8-aa3a-f9dd6d2995fb.json
25408   /software/<username>/python3 -m bash_kernel -f /tmp/tmpg03sodnd.json

**Comment by BoPeng** [comment]
It looks like you have two instances of sos kernel running and one bash kernel. It would help if you could shutdown all jupyter servers, kill all zombies (sos, R, bash kernels and processes), start a single jupyter server, and try to reproduce the problem.

**Comment by BoPeng** [comment]
@MatteoSchiavinato Trying to see if you are still experiencing the same problem.

**Comment by MatteoSchiavinato** [comment]
I don't know why I haven't answered, now 1.5 years ago. Anyway, I am not experiencing it anymore.

**Comment by BoPeng** [comment]
Thanks. Feel free to let me know if you have any other concerns or suggestions.
