### ISSUE TITLE
Remove %set?

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos-notebook#231]
With the removal of signatures in interactive mode (#230 ), `%set` becomes even less useful than before. 

The idea with `%set` was to set parameters for the execution of scratch cell, and it was also expanded to add default parameters to `%run`. However, because scratch cells only accept a single step, none of the workflow specific options are applicable. Therefore, the only options that appear to be useful would be `%set -v2` and `%set -s force`. Now that `%set -s force` is overridden by #230. The only legitimate use case left is `%set -v2`.

`%set` is also used to set default parameter for `%run` etc, but it is generally a bad idea to set parameters implicitly.

So in the end we could remove the `%set` magic as long as we can find a replacement for `%set -v`. Actually, `%debug on` already has some of it.

**Comment by gaow** [comment]
I have not used this magic anyways -- guess it is another way to say I am in favor of removing it :P
