### ISSUE TITLE
Widget support for SoS Notebook.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos-notebook#234]
SoS kernel blocks communication between kernels and frontend so that progress bar and other widgets from subkernels stopped working. We ignored this problem before but should try to address it now.

The following is just an example from tqdm webpage:

```
from tqdm import tnrange, tqdm_notebook
from time import sleep

for i in tnrange(3, desc='1st loop'):
    for j in tqdm_notebook(range(100), desc='2nd loop'):
        sleep(0.01)
```

![image](https://user-images.githubusercontent.com/9889312/61005988-e2c69900-a32e-11e9-8373-a499bba06b1f.png)

**Comment by BoPeng** [comment]
Similar effect in 

```
import ipywidgets as widgets
widgets.IntSlider()
```

![image](https://user-images.githubusercontent.com/9889312/61006191-5cf71d80-a32f-11e9-8a90-776125407b0a.png)

**Comment by BoPeng** [comment]
This is the illustration and we need to think how to insert the SoS kernel in it.

https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20Low%20Level.html

![image](https://user-images.githubusercontent.com/9889312/61006408-df7fdd00-a32f-11e9-8825-f659e5d9810c.png)

**Comment by BoPeng** [comment]
![image](https://user-images.githubusercontent.com/9889312/61193908-d9696380-a683-11e9-9fcc-2a73e3bb7ac5.png)

Output of widgets works, but interactions still not (frontend sending message to subkernel directly).

**Comment by BoPeng** [comment]
Note that `ipywidget` saves `parent_header`'s `msg_id` for internal use, and we will need to keep `msg_id` consistent.

https://github.com/jupyter-widgets/ipywidgets/blob/67af059687205f10a339472f72cd86d2b34948c2/ipywidgets/widgets/widget_output.py#L50-L55

**Comment by BoPeng** [comment]
Try to organize my thought on what is happening:

1. When SoS execute a cell, an `execute_request` is sent and returns a `msg_id` (let us name it `sos_msg_id`). This is the "master message" for the cell, and should be the `parent_header` of all messages if anything needs to be displayed in the notebook.

2. SoS calls `run_cell` and send the code to the subkernel with another `execute_request` message, which returns another `msg_id` (named `subkernel_msg_id`).

3. SoS monitors output from the kernel. All messages have a `parent_header` of the `subkernel_msg_id`. SoS resend the messages with `sos_msg_id` so that they can be displayed in SoS notebook.

The problem with widgets is that the widgets are created with the `subkernel_msg_id`. Here are what will happen

1. If we send `comm_open` messages with `sos_msg_id`, the widget will not work because the sos kernel does not handle widget.

2. If we send `comm_open` messages with `subkernel_msg_id`, the widget will not be displayed because the header IDs are different.

It seems necessary to translate the IDs or force the use of `sos_msg_id` in `subkernel_msg_id`.

**Comment by BoPeng** [comment]
OK, the frontend `comm_msg` works like this:

1. When the subkernel sends `comm_open` message, the SoS kernel can record who is creating what `comm`.
2. When the user presses a frontend widget, some `comm_msg` will be sent to the `SoS` kernel.
3. The SoS kernel looks up the subkernel and forward the `comm_msg` to the subkernel.
4. The subkernel sometimes sends some responses to `ioPub`
5. The SoS kernel catches and forward it to the frontend.

The problem is with 4, because SoS does not actively listen to `comm_msg` messages from iopub subkernels (it only checks it when the subkernel is being executed). Therefore the SoS will not be able to process the `comm_msg` in time.

To solve this problem, the SoS kernel will have to actively check `ioPub` channel of all subkernels and forward `comm_msg` to the frontend.

**Comment by BoPeng** [comment]
Finally, the solution is to add a function that forward all ioPub messages to frontend even when no cell is being evaluated. This allows frontend actions to be handled by the SoS kernel.

![image](https://user-images.githubusercontent.com/9889312/61341757-52e08d80-a80d-11e9-8b63-a9a834cd359c.png)


The function is called by the controller in the controller's messaging loop in a separate thread so it responds a bit slower than the native widgets.

**Comment by ktaletsk** [comment]
Hi @BoPeng , thank you for this fix! I can't make it fully working for me, though. I am able to create the widget in Python3 subkernel and interact with it, but the number below is not updated. It is working fine in the SoS kernel or in vanilla Python3 notebook. It is possible that I am not installing something properly, so I give the sequence of steps below:

1. Use the latest jupyter-minimal container:
	```
	docker run -it -p 8888:8888 jupyter/minimal-notebook:307ad2bb5fce /bin/bash
	```

2. Install ipywidgets, verify they work
	a. conda install -c conda-forge ipywidgets
	b. jupyter labextension install @jupyter-widgets/jupyterlab-manager
	c. Start Jupyter Lab
	d. Create a notebook with the following cell:
		```
		from ipywidgets import interact, interactive, fixed, interact_manual
		import ipywidgets as widgets
		def f(x):
    		return x
		interact(f, x=10);
    	```
    e. It works
 
3. Install SoS and try interactive widgets again
	a. pip install sos==0.19.14 sos-notebook==0.19.14 sos-python==0.18.1
	b. python -m sos_notebook.install
	c. jupyter labextension install jupyterlab-sos
	d. Start Jupyter, choose SoS kernel, choose Python3 subkernel
	e. Run the same cell
	f. The number below is not updated and stays at 10
<img width="1264" alt="Screen Shot 2019-07-31 at 1 42 49 PM" src="https://user-images.githubusercontent.com/8834829/62238923-8ab50c80-b399-11e9-91c4-7104c689afa4.png">

**Comment by ktaletsk** [comment]
Update: the same problem if installing from the latest GitHub version (which I should have used):
```
pip install git+https://github.com/vatlab/sos
pip install git+https://github.com/vatlab/sos-notebook.git
pip install git+https://github.com/vatlab/sos-python.git
```

**Comment by BoPeng** [comment]
I only tested for classic jupyter and I am testing JupyterLab now. It is likely that `jupyterlab-sos` is not playing well with `@jupyter-widgets`.

**Comment by ktaletsk** [comment]
@BoPeng you are right indeed. If I do not install `@jupyter-widgets`, widgets are fully working in the classic notebook, but obviously not in the JupyterLab. If I install `@jupyter-widgets`, it does not work anywhere, not classic, not JupyterLab

**Comment by BoPeng** [comment]
Here with `@jupyterlab-widgets` installed widgets in classic jupyter works... As far as I can tell the sos kernel is sending the correct messages to the frontend and I am trying to figure out why the linked number is not updated.

**Comment by BoPeng** [comment]
I finally understand what is going on here but I am not sure if I can find a solution. Allow me to explain the problem in detail:

![image](https://user-images.githubusercontent.com/9889312/62340151-25017700-b4a4-11e9-9cad-f42a4c282b8a.png)

1. When the slide is clicked, a `comm_msg` is generated, and is sent to the subkernel directly. (Python3 in this case).
2. The subkernel respond with a series of messages, `status` (busy), `comm_msg`, `clear_output`, `display_data`, `comm_msg`, and `status` (idle). These messages are [forwarded by `SoS` to the frontend](https://github.com/vatlab/sos-notebook/blob/master/src/sos_notebook/kernel.py#L1661), and updates the widget. 

This is how widget is supported by SoS Notebook. 

In JupyterLab, the same messages are sent but the frontend is not updated. The problem here is that

1. When the slide is clicked, a `comm_msg` is generated, and is sent to the subkernel directly. (Python3 in this case).
2. The SoS kernel sent messages `status` (busy) and `status` (idle) to the frontend. Because [the future set for `comm_msg`](https://github.com/jupyterlab/jupyterlab/blob/master/packages/services/src/kernel/default.ts#L333) is resolved by the acceptance of `status` (idle), the `comm_msg` future is removed from `this._futures`.
3. When a series of messages are sent from subkernel to frontend, they are ignored because the parent message `comm_msg` has already been resolved.

So the difference between classic Jupyter and JupyterLab is the `status` response of the SoS kernel to the `comm_msg`. The only "proper" solution seems to put the SoS kernel in busy mode with `comm_msg`, but this is currently not possible because `comm_msg` is directly sent to the subkernel.

**Comment by BoPeng** [comment]
@ktaletsk I have submitted a patch. Please let me know if widget support is still not working on your side.

**Comment by ktaletsk** [comment]
@BoPeng it is working, thank you!
