### ISSUE TITLE
`__max_procs__` attribute in notebook

### ISSUE THREAD

**Issue by gaow** [vatlab/sos-notebook#237]
Using current `master` of SoS and pip release of sos-notebook,

![2019-08-08-11-45-21_scrot](https://user-images.githubusercontent.com/917985/62721579-1f3ef080-b9d2-11e9-9d38-5478930e44fa.png)

**Comment by BoPeng** [comment]
Yes I changed the name to [`__worker_procs__`](https://github.com/vatlab/sos/blob/master/src/sos/__main__.py#L229) because `-j` is no longer `__max_procs__`. I am in a call now but you can make the change and push.

**Comment by BoPeng** [comment]
Fix have been fixed, but `sos` is not stable yet.

**Comment by gaow** [comment]
Sorry I was in a call earlier too today then a one-to-one meeting. Thanks for the fix!

> but sos is not stable yet.

It seems all tests pass, right?

**Comment by BoPeng** [comment]
> It seems all tests pass, right?

Yes, also more work will be in a branch if needed.

**Comment by gaow** [comment]
Sorry another bug here 

![2019-08-08-16-29-27_scrot](https://user-images.githubusercontent.com/917985/62739156-cf741f80-b9f9-11e9-99ac-db1d14134bb9.png)

I reopen this issue instead of opening a new one ...

**Comment by BoPeng** [comment]
Should have been more careful.

**Comment by gaow** [comment]
Currently SoS `master` is still broken. I've got a workflow that now throws error but it is not minimal. So hopefully after tests pass I'll be able to use it.

**Comment by minqiao** [comment]
The notebook is still not quite right

![Screenshot from 2019-08-08 17-32-10](https://user-images.githubusercontent.com/20076829/62742028-97bda580-ba02-11e9-88fb-ca92fa68fac0.png)

**Comment by BoPeng** [comment]
The default value of that parameter has been changed from ncpu/2 to None in order to process cluster environment variables. I am just wondering if sos notebook needs to change accordingly ... so that they can also have cluster workers..

**Comment by BoPeng** [comment]
Please try again, I suppose there is no need to support starting sos notebook on cluster, at least now.

**Comment by gaow** [comment]
Great it is fixed!
