### ISSUE TITLE
A stand alone utility for data format exchanges

### ISSUE THREAD

**Issue by gaow** [vatlab/sos-notebook#24]
I'm not sure how difficult it is, but I'd very much like it if it is possible to isolate the SoS data model into some SoS utilities to converting data between different languages for SoS workflow, just like what SoS notebook does. I'd like to contribute to the coding since I need the feature myself :) just want to discuss here the feasibility and a proper interface.

**Comment by BoPeng** [comment]
What is the context of this request? In sos? The problem here is that the jupyter kernels are all alive so that sos can execute commands on both ends to facilitate variable exchange but that is a different case for workflow engine.

**Comment by BoPeng** [comment]
The new DataBus discussions are quite relevant to this but right now, sos is implemented towards 

```
%get var --from B
```
so only one command will be used. With a DataBus implementation, the magic could do something like

```
%put_to_bus var --in B
%get_from_bus var --in A --remove-after-done
```
in the background, and which should essentially be what is happening from language modules.
