### ISSUE TITLE
Best way to implement SoS notebooks as cli driven parameterised scripts

### ISSUE THREAD

**Issue by sonnylaskar** [vatlab/sos-notebook#247]
Hi,

Thanks for building this amazing piece of software.
Let me give you some background of our use case.

**Use Case**: Run a Jupyter notebook from CLI / Python which allows passing runtime parameters and generate the output as another notebook
__Current Solution:__
We use *papermill* to execute the notebook via CLI / Python and pass runtime parameters. It works very well. I know that papermill is not supported with SoS notebooks.
*Challenge*: Jupyter notebooks allow usage of a single kernel only and hence we want to use SoS

**Simple Scenario:**
Assume we have the below SoS notebook.
![image](https://user-images.githubusercontent.com/7631261/64985294-2e269600-d8e2-11e9-9f9e-1993172a7d8f.png)

The first cell uses Python3 kernel to define some variables.
The second cell uses Bash kernel to get the variable from Python3 kernel and do some stuff

We want to be able to run this SoS notebook via CLI or within a Python script which can take the value of that variable as arguments and generate an output notebook file.

Please let me know if this is possible or whatever closest is possible.

Thanks

**Comment by BoPeng** [comment]
This problem has been recently discussed #245.

Essentially speaking, the kernel information (cell meta) is not passed by papermill so SoS will not know what kernel to use to execute the next cell. If you have to use papermill, some work has to be done (e.g. PRs to papermill) to make papermill SoS-aware.

SoS has its own facility `sos convert -e`, which execute a workflow using an execution mechanism of nbconvert, but it does not support all SoS features (at least not all features are tested).

The best bet is actually using selenium to execute the notebook in a hidden browser. In this way all frontend features will be properly supported. This is essentially how our test suite runs so technically it is doable. We just have not decided if we should use this approach, and if we do, if it deserves a separate interface, or replace `sos convert -e`.

**Comment by BoPeng** [comment]
I can see that papermill is just nbconvert with a [customized preprocessor](https://github.com/nteract/papermill/blob/e7e83debf6e55a8051eb7b02d178d789dcc9a5f9/papermill/preprocess.py#L8). SoS' `sos convert -e` also has its [own preprocessor](https://github.com/vatlab/sos-notebook/blob/master/src/sos_notebook/converter.py#L149) that passes meta data between cells. I am not quite sure but it is possible to do something like

1. Improve and probably refactor sos preprocessor
2. In papermill, if the kernel is `sos`, import `sos`'s preprocessor and merge its function to papermill preprocessor.

Perhaps someone can try to work on this?

**Comment by sonnylaskar** [comment]
Hi, me and my colleague will try to help in whatever way possible.
Let me know what needs to be done.

**Comment by BoPeng** [comment]
@sonnylaskar Thanks. I have just created the [`sos-papermill` repo](https://github.com/vatlab/sos-papermill). I am not sure how you can help but you can at least test it and submit tickets there. I might also ask question there and ping you.

**Comment by BoPeng** [comment]
@sonnylaskar and @ktaletsk, I have just created and uploaded sos-papermill 0.1.0 with repo [`sos-papermill` repo](https://github.com/vatlab/sos-papermill). It is a quick and dirty implementation of the sos engine for papermill, please feel free to test and submit bugs and/or PR there.

To use it
```
pip install sos-papermill
papermill --engine sos from.ipynb to.ipynb
```
