### ISSUE TITLE
Deprecating automatic variable transfer

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos-notebook#253]
We currently have a feature that variables with names starting with `sos` are transferred implicitly. 

This looks like a decent feature but it comes at a cost that all languages need to check if there are variables with names starting with `sos`, each time when a kernel switch happens. This can be a performance issue, and it makes it a bit difficult to implement language modules since not all languages can check variables easily.

I am wondering if we can disable this feature, and/or replace it with something like

```
%global myvar
```

to have explicit specification of "cross kernel" variables.

**Comment by gaow** [comment]
I think it is good idea to make the transfer explicit. It's not lots of typing and it would be nice to explicitly declare all global variables.

**Comment by BoPeng** [comment]
It is ok to remove auto transfer, but do you like the %global magic? Is this a good name?

**Comment by gaow** [comment]
I think it is a good name; otherwise `%shared`?

**Comment by BoPeng** [comment]
It is a bit awkward to remove a feature that I have been introducing in my talks, but I think explicit is better than implicit, especially because we are in Python camp.

Note that the implicit stuff was inspired by Beaker Notebooks, and it is the only method there.

**Comment by BoPeng** [comment]
`global` may lead to the perception that the variables are in some global place and cannot be modified in subkernels. `shared` is better in this sense although it may be understood of a single cross-kernel instance. 

However, the `global` concept can be useful in case we do not want the variables to change values, because one problem with the current variable transfer is that variables can change values after kernel switch. For example, if we say

```
%global a = 12345678901234567890
```
if will be a double in R, and if we switch back then `a` will be double in SoS again, so having a "readonly" global variable that will keep its value in SoS can be useful. That is to say, instead of introducing something that can be done with `%get`, we might be able to introducing something different and conceptually clearer.

**Comment by BoPeng** [comment]
![image](https://user-images.githubusercontent.com/9889312/65287417-cdc56d80-db08-11e9-870d-a1bc98798ce6.png)

**Comment by BoPeng** [comment]
Implemented in the `global_magic` branch. It more or less works, but complications arise if users change the global var in a subkernel. Because the global variable will be re-sent to the subkernel each time, the user-changed value will be overwritten, leading to confusion.

**Comment by BoPeng** [comment]
Global defined from subkernel

![image](https://user-images.githubusercontent.com/9889312/65295025-ab8e1880-db25-11e9-98f2-0f4876e0387b.png)

**Comment by BoPeng** [comment]
`%global` would put variables to SoS kernel, overriding existing values.

![image](https://user-images.githubusercontent.com/9889312/65295177-2a835100-db26-11e9-94c1-dc35b469135f.png)

**Comment by BoPeng** [comment]
Basically if the users only defines `global` in SoS and do not override it anywhere, it could be useful to "broadcast" variables to all subkernels (even if they have not started yet). Otherwise the behavior could be confusing.
