### ISSUE TITLE
Report V2 template problems

### ISSUE THREAD

**Issue by gaow** [vatlab/sos-notebook#273]
I was checking out the new `sos-report-toc-v2` and `sos-report-v2` templates and noticed an issue at least on my Chrome on Debian 9. When I switch from Read Only to Show Code, for example, then switching back to Read Only does not work.

**Comment by BoPeng** [comment]
Could you PM me the HTML file?

**Comment by gaow** [comment]
Sure -- see below (please remove .txt extension)

[test.html.txt](https://github.com/vatlab/sos-notebook/files/3861766/test.html.txt)

**Comment by BoPeng** [comment]
Update and retry please.

**Comment by gaow** [comment]
Great it works now!
