### ISSUE TITLE
xonsh Kernel

### ISSUE THREAD

**Issue by WardThomas** [vatlab/sos-notebook#274]
Hello Bo Peng, thanks for sharing Sos.
Would it be possible to add Xonsh as an SoS sub kernel? 

I see you use the metakernel/Calysto bash as a base for your bash sub kernel and that there is a metakernel/Calysto xonsh as well, so maybe it would be fairly easy to add xonsh?

https://nbviewer.jupyter.org/github/Calysto/xonsh_kernel/tree/master/

regards

**Comment by BoPeng** [comment]
@WardThomas I am closing this ticket since the upstream has not been fixed. I will re-open this ticket if Calysto/xonsh_kernel#13 is fixed.
