### ISSUE TITLE
SoS kernel not listed in kernel specs after successfully installed sos notebooks

### ISSUE THREAD

**Issue by bspeiche223** [vatlab/sos-notebook#283]
Hi! I've been very excited to try out sos notebooks, so I've followed this tutorial (https://www.youtube.com/watch?time_continue=5&v=TxcPwyCVa8Y) to set it up. I've installed the newest Python and R versions as shown in the video and followed the steps after installing sos, sos notebooks, etc. Unfortunately, 
sos won't show up for 'jupyter kernelspec list'. I've also pip installed sos-R which also won't show up, all I'm getting is Python3. 

<img width="515" alt="Screen Shot 2020-04-07 at 9 40 48 AM" src="https://user-images.githubusercontent.com/63308970/78696138-df5b4080-78b3-11ea-9336-e2d8688c0cdd.png">

Any help or guidance here would be very much appreciated. Thank you!

**Comment by BoPeng** [comment]
Did you use conda or system Python? If you only see the python3 kernel, you will need to install R kernel and make sure it works before you install the language modules for R. Please have a look at sections for specific sections of https://vatlab.github.io/sos-docs/running.html if you have not checked it.

**Comment by BoPeng** [comment]
I assume this has been resolved.
