### ISSUE TITLE
bash sub-kernel evaluation queued for a very long time

### ISSUE THREAD

**Issue by kundeng** [vatlab/sos-notebook#285]
for i in `seq  1 10`
  do 
     echo $i
  done

very simple loop, not sure why it gets queued for a very long time.  I restarted the meta-kernel (along with all sub kernels) and rerun and it worked.  So not sure what happened there.

**Comment by BoPeng** [comment]
I cannot reproduce the problem either... could help if you can provide more information on the kernel(s) involved.

**Comment by BoPeng** [comment]
Cannot reproduce.
