### ISSUE TITLE
Overlapping text in side panel

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos-notebook#3]
![image](https://user-images.githubusercontent.com/9889312/31963803-8da44812-b8c7-11e7-8ce5-b58334c78215.png)

The text is supposed to show the number of lines.

**Comment by Qwertyuiop21672** [comment]
What is the URL of the website so I can actually take a look at it?

**Comment by BoPeng** [comment]
The same. Something advanced.

**Comment by BoPeng** [comment]
Fixed.
