### ISSUE TITLE
Syntax highlighting for custom language modules

### ISSUE THREAD

**Issue by sillymoi** [vatlab/sos-notebook#326]
Hi,

I'm trying out sos notebooks with multiple homegrown kernels supported by a single sos language plugin. All of the kernels are using the same input language (RDF turtle in this case), and I'd like to enable syntax highlighting in the cells. Following the discussion around C++, I added the codemirror mode to imports of sos-notebook, as well as to the `modeMap` and `extMap` in kernel.js. What I'm missing is how to tell sos which mode to use, I'm not sure if the problem is in my plugin, the mode definition in kernel.js... or something else.

Thanks for any pointers :)

**Comment by BoPeng** [comment]
Does this RDF Turtle kernel has a concept of "variable", namely, it is worthwhile to define a language module to pass variables around?

**Comment by sillymoi** [comment]
Not really, no... it's just a front to send HTTP requests with the given payload (alongside some decoration), similar to SPARQL modules - there are no variables in pythonic sense, but query results could be passed around in a similar way, I'm still not there yet. 

At start, I defined the language module mainly to specify the color of the cells. Is there some other way you can suggest?

I made some changes recently, seems that adding this to language_info of the kernel itself helped sos set the mode correctly:
```python
class MyKernel(Kernel):
    language_info = {'name': 'turtle',
                                 'codemirror_mode': 'turtle',
                                 'file_extension': '.ttl',
                                 'mimetype': 'text/turtle'}`
...
```
Is that correct, that's how sos determines the mode?

**Comment by BoPeng** [comment]
Could you send me url for the kernel.

I want to use config file for this and solve the problem once for all.

**Comment by sillymoi** [comment]
I don't have it on github right now, will push and send the link later.

Den ons 18 aug. 2021 12:46Bo ***@***.***> skrev:

**Comment by BoPeng** [comment]
@sillymoi Any update?

**Comment by sillymoi** [comment]
https://github.com/sillymoi/turtle-kernel try this one,  enter whatever and the kernel will output a small turtle code example. 'plain' jupyter does the highlighting:

![image](https://user-images.githubusercontent.com/4181251/130368419-a48aeaa3-79f6-402e-bd04-43dade8d60fe.png)

 sos looks different:

![image](https://user-images.githubusercontent.com/4181251/130368436-91221dae-791b-435d-b9df-f1aab2b45428.png)

note that i added turtle codemirror mode `codemirror/mode/turtle/turtle` to kernel.js imports (define[..]) in sos_notebook, and also `ttl: "turtle"` to extMap, `turtle: "turtle"` to modeMap.

**Comment by BoPeng** [comment]
Thanks. Could you push your changes as a PR so that I can try it?

**Comment by sillymoi** [comment]
there it is

**Comment by BoPeng** [comment]
@sillymoi I have fixed the issue. Please test it if you get some time. Basically, you will need to

1. install the master branch of sos-notebook. 
2. Run `python -m sos_notebook.install`, due to some complications with most reent version of `jupyter_client`, you will need to use an `async` kernel manager for jupyter, I have the issue listed in the output of the `install` command
3. Add `"turtle": "turtle"` to `~/.jupyter/nbconfig/notebook.json` and start jupyter notebook
