### ISSUE TITLE
Python kernel (without sos-python) does not work

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos-notebook#328]
![image](https://user-images.githubusercontent.com/9889312/133890844-e9cc02fa-d36d-4857-a887-97da49ce8497.png)

**Comment by BoPeng** [comment]
This is getting complicated because jupyter notebook itself does not work well with the new version of `jupyter_client` by default.

see https://github.com/jupyter/notebook/issues/6164

**Comment by BoPeng** [comment]
@zoq I think I have fixed sos-notebook and jupyterlab-sos, could you please test them?

**Comment by BoPeng** [comment]
It is the async branch.

**Comment by zoq** [comment]
@BoPeng Awesome works great, tested with the C++, JavaScript and Python3 kernel.

**Comment by BoPeng** [comment]
Thanks. I have released sos-notebook 0.22.7, and will release a conda-forge version soon.
