### ISSUE TITLE
Syntax to separate sos and subkernel magic?

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos-notebook#33]
Right now sos handles sos magics and send the rest of the cell content to subkernels. There is however a slight chance that a subkernel defines the same magic as SoS, so

```
%get
blah
```
will cause some problem if `%get` is supposed to be sent to the subkernel.

I suspect that we can add some syntax to separate sos magics and subkernel magics, something like

```
%get var --from R
%
%get
```

Not that we have a similar problem with `#` and `!` so in case the subkernel actually handles `#` or `!`, we should perhaps do something like

```
%
! something for subkernel
```
The separator could be `%`, `%stop`, or `%--`, or two blank lines...

**Comment by gaow** [comment]
I have to admit that i do not use enough `magic` to bring very good ideas to the discussion table ... But a `%--` separator, if i have to choose, looks best.

**Comment by BoPeng** [comment]
With the change, it is now possible to separate sos and subkernel magics by a new line.
