### ISSUE TITLE
R does not work 

### ISSUE THREAD

**Issue by msh855** [vatlab/sos-notebook#332]
Hi,

I installed SoS polyglot, but R does not work. 

I used conda to install SoS locally

I get this error when I am trying to use R in Jupiter Notebook. 

![image](https://user-images.githubusercontent.com/26636184/135528841-62055c3a-2304-47fb-bded-fea715b5ef38.png)

**Comment by BoPeng** [comment]
Please check

1. If r works "normally" outside of SoS notebook.
2. If Python kernel works inside of SoS notebook (after installing sos-python)
3. if you have installed sos-r

If all answers are yes, please send me output of `jupyter kernelspec list --json` as a start.

**Comment by msh855** [comment]
Thanks. Indeed case 1 fails to run in Jupyter ( R works normally outside any python env, e.g. via my Rstudio). I will investigate, but happy if you have any thoughts.

**Comment by BoPeng** [comment]
There are many tutorials but you can check https://vatlab.github.io/sos-docs/running.html#r

**Comment by msh855** [comment]
Thank you that is great. For the record, I fixed the problem with iRkernel and Jupyter. The solution it worked for me I found it here: https://stackoverflow.com/questions/44056164/jupyter-client-has-to-be-installed-but-jupyter-kernelspec-version-exited-wit 

I will give now a shot to see if SoS would run smoothly after this.
