### ISSUE TITLE
Running multiple kernels from one notebook : error "asyncio.run() cannot be called from a running event loop"

### ISSUE THREAD

**Issue by MedAdh42** [vatlab/sos-notebook#339]
Hello,
I'm trying to use SOS-notebook to use multiple kernels at once, there an issue with a particular kernal (ParaView-5.8.1 see image) this kernel is customed therefore not supported, it connects Jupyter with the ParaView visualisation software.

Is there a way to run this kernel on a another thread?   

![sos](https://user-images.githubusercontent.com/70356073/180019169-ac99d1c9-f893-4ee9-b579-ed0f543c7a9a.PNG)

**Comment by Mohamed-AIDAHI** [comment]
Indeed my [kernel](https://gitlab.kitware.com/paraview/paraviewjupyterkernel) doesn't support async, is there anyway still to use it within SOS-notebook
