### ISSUE TITLE
Porting SoS Notebook to JupyterLab.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos-notebook#45]
As JupyterLab [turnning beta](https://blog.jupyter.org/jupyterlab-is-ready-for-users-5a6f039b8906), we should gather some speed to port SoS Notebook to JupyterLab. JupyterLab plans to release its 1.0 version at later 2018, which should be our goal as well.

This ticket will track the status of JupyterLab port and provide key information on technical issues.

### SoS Kernel + SoS Workflow engine

This part seems to be usable directly in JupyterLab.

### Side panel -> SoS Console

Our single-cell side panel should be replaced by a SoS Console. Contents from SoS Notebook will be sent to and be displayed at this console. The console and notebook will be backed by the SoS kernel managing multiple subkernels. 

### UI improvements such as language selection boxes

It is unclear how to do this before checking the developer guide. It is likely that it will be provided as an extension.

### Magics and shortcuts

These have to be examined one by one, but most likely they will work just fine.

**Comment by tom-dyar** [comment]
Bo -- count me in to help with this!

**Comment by BoPeng** [comment]
@tom-dyar Thanks for your interest. I cannot tell much from your github profile, what is your expertise? What area do you plan to work on? We are still trying to learn how to write extensions for JupyterLab and plan to create a JupyterLab branch to experiment things.

**Comment by tom-dyar** [comment]
I am a bioinformatics programmer with a fair amount of python experience. I have developed software for my employers mostly, but can devote some time to this project since I will use SoS for work projects. I imagine I can commit about 0.5 days per week on average, so not much ;)

—
Thomas Dyar
Bioinformatics Scientist
Biogen, RTP, NC
m: 919.599.8874
________________________________

**Comment by BoPeng** [comment]
Just to show that the SoS kernel works in JupyterLab, so most of the work should be with the frontend and frontend <-> backend communication. I suppose we first need to figure out the JupyterLab counterpart of [kernel.js](https://github.com/vatlab/sos-notebook/blob/master/src/sos_notebook/kernel.js): what to use (`typescript`?) and how to install it (currently `python -m sos_notebook.install` install `kernel.js` with sos  kernel spec).

![image](https://user-images.githubusercontent.com/9889312/36634195-6afc53ea-1966-11e8-9bcd-737857db429e.png)

**Comment by BoPeng** [comment]
Just created a [jupyterlab branch](https://github.com/vatlab/sos-notebook/tree/jupyterlab)

**Comment by tom-dyar** [comment]
Thanks, @BoPeng -- I think I will look at how tab-completion works in JupyterLab, since that doesn't work on my Mac installation of SoS... If you think there are some steps to take before playing with that, I am all ears. I have Python experience, but no TypeScript or javascript knowledge, so it will take awhile to get up to speed on that ;)

**Comment by BoPeng** [comment]
Tab completion is implemented in the kernel and appears to be working for me in JupyterLab (tried `!ls <TAB>`). The completer is implemented in [completer.py](https://github.com/vatlab/sos-notebook/blob/master/src/sos_notebook/completer.py) and triggered from [here](https://github.com/vatlab/sos-notebook/blob/master/src/sos_notebook/kernel.py#L1169). You should be able to trace to the completer if things are not working as you would expect.

**Comment by gaow** [comment]
It would be helpful to port syntax highligher to JupyterLab at an early stage -- that way at least it is a decent SoS editor to use :)

**Comment by BoPeng** [comment]
I believe that the codemirror syntax highlighter should be separated from the kernel in JupyterLab. JupyterLab provides a nice editor and viewer and allows [registration of extensions for other mime types](https://github.com/jupyterlab/jupyter-renderers). I believe that we can define an extension for `.sos` mime type so that JupyterLab can be used to edit text-based `.sos` files. Then it should be able to use registered `.sos` syntax highlighter directly in Jupyterlab.

One stone for two birds.

**Comment by BoPeng** [comment]
Moved to sos-extension repo.
