### ISSUE TITLE
Separate colors for languages sharing the same language module

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos-notebook#48]
Current prompt color is defined for each language module, so language sharing the same language modules (e.g. matlab and octave, python2 and python3, javascript and typescript, ...) would be marked by the same color in the notebook. Perhaps we should define colors at the language level, not at the module level.

**Comment by HenryLeongStat** [comment]
I agree, it would be more clear. I think the colors for languages using the same module can be similar.
Let me paste a sample here to see how it looks like.

**Comment by HenryLeongStat** [comment]
<img width="242" alt="screen shot 2018-03-02 at 8 58 02 pm" src="https://user-images.githubusercontent.com/26916551/36929868-989153a0-1e5c-11e8-99d9-f32e6f2b21ad.png">
<img width="234" alt="screen shot 2018-03-02 at 8 57 55 pm" src="https://user-images.githubusercontent.com/26916551/36929870-9b605f72-1e5c-11e8-83d5-6ace774e2619.png">

Change Python 2, Octave to a little bit darker. (Assuming Python 3 and MATLAB are more popular than those two)

**Comment by BoPeng** [comment]
What I would do is:

1. Start Chrome, go to the features page
2. Right click, inspect
3. Check color from the inspect window

Adjust and send screenshot like the following 
![image](https://user-images.githubusercontent.com/9889312/36929923-55d26cf6-1e5d-11e8-882e-b6d7d7d0a1f8.png)

**Comment by BoPeng** [comment]
I think matlab can take the darker cyan in the icon. Python 3 can be a bit darker than python 2 (the icon seems to be darker). Not sure about typescript though.

**Comment by BoPeng** [comment]
You also need to show the HEX code of the proposed color.

**Comment by HenryLeongStat** [comment]
I see! 
<img width="600" alt="screen shot 2018-03-02 at 9 13 56 pm" src="https://user-images.githubusercontent.com/26916551/36930012-b0de7fe4-1e5e-11e8-928a-6fe6f5cd3bcb.png">

HEX code of the color of `Python 3` is: ffd91a
HEX code of the color of `Matlab` (Should we change it to `MATLAB`?) is: 8ee7f1

**Comment by HenryLeongStat** [comment]
For `TypeScript`, choosing color based on its logo seems being easy to get conflict with `SAS` ...

**Comment by BoPeng** [comment]
Looks good.  How about typescript? Make it greener?

**Comment by BoPeng** [comment]
But the domestic Nate color for typescript from its homepage is dark blue.  Does it look very bad in Jupyter? You can try it with %use R —color xxxxxx

**Comment by BoPeng** [comment]
I meant dominate.

**Comment by HenryLeongStat** [comment]
9fff80 <img width="304" alt="screen shot 2018-03-02 at 9 32 01 pm" src="https://user-images.githubusercontent.com/26916551/36930163-2b1b1248-1e61-11e8-911d-31d8ffe59b12.png"> 
06324B (Dark colors are bad! As we discussed before) 
<img width="290" alt="screen shot 2018-03-02 at 9 32 42 pm" src="https://user-images.githubusercontent.com/26916551/36930174-595715da-1e61-11e8-9ba3-52a3d4071fac.png">
56A6DC (Based on some buildings on `TypeScript`'s website) 
<img width="294" alt="screen shot 2018-03-02 at 9 33 43 pm" src="https://user-images.githubusercontent.com/26916551/36930181-89287538-1e61-11e8-8136-060304fabe2f.png">
<img width="670" alt="screen shot 2018-03-02 at 9 35 07 pm 1" src="https://user-images.githubusercontent.com/26916551/36930185-a7e4f802-1e61-11e8-80cf-32dc87cc9b0f.png">

**Comment by BoPeng** [comment]
How the last one differ from the one for sas? Need to put them together to see.

**Comment by HenryLeongStat** [comment]
It's quite different, but looks bad... 

<img width="236" alt="screen shot 2018-03-02 at 9 40 09 pm" src="https://user-images.githubusercontent.com/26916551/36930246-5090ab22-1e62-11e8-8b61-8c95f59c3de5.png">

**Comment by HenryLeongStat** [comment]
I know, simply update `Feature.ipynb`.

But how to update the `kernel.py` for `Python` and `MATLAB`?

```

class sos_Python:
    supported_kernels = {'Python3': ['python3'], 'Python2': ['python2']}
    background_color = '#FFE771'
    options = {
        'variable_pattern': r'^[_A-Za-z0-9\.]+\s*$',
        'assignment_pattern': r'^([_A-Za-z0-9\.]+)\s*=.*$'
        }
...
...
```

I guess it should be like the followings:
```
if kernel_name == 'python3':
    background_color = 'ffd91a'
```
But where should I put them into? After `__init__` or?

**Comment by BoPeng** [comment]
We need to make background_color a dictionary, which is not too hard but it is difficult to keep backward compatibility.

**Comment by HenryLeongStat** [comment]
Not quite understand that... Why can't we check it by using the `if statement`?

**Comment by BoPeng** [comment]
Basically, if you make it a dictionary

1.  current `sos_notebook` + new language module = fail
2. updated `sos_notebook` + old language module ?? Difficult because `sos_notebook` need to be updated to handle both cases
3. updated `sos_notebook` + updated language module = ok

**Comment by HenryLeongStat** [comment]
Didn't get it.. Even though `background_color ` is a dictionary, `kernel_name` still needs to be checked, doesn't it?

 Let me update `Feature.ipynb` first.

**Comment by BoPeng** [comment]
Look at [this line of code](https://github.com/vatlab/sos-notebook/blob/master/src/sos_notebook/kernel.py#L728), sos notebook gets the color from the class definition. If you change [`background_color` of matlab](https://github.com/vatlab/sos-matlab/blob/master/src/sos_matlab/kernel.py#L45) to something like `{'matlab": 'color1', 'octave': 'color2'}`, sos notebook side would fail.

**Comment by BoPeng** [comment]
What we can do is to leave `background_color` as it is, and define a new interface, something like

```
background_color = 'old_color'

def get_background_color(self, lan):
    if lan == 'octave':
           return old_color
    else:
          return new_color_for_matlab_or_unknown
```

Then the old version of `sos_notebook` will still work, and the updated `sos_notebook` will do something like

```
def get_color(plugin, lan):
    if has_attr(plugin, 'get_background_color'):
        return plugin.get_background_color(lan)
    else:
        # see an old language module that does not have the new function
        return plugin.background_color
```
and replace 
```
plugin.background_color
```
with
```
get_color(plugin, ???)
```

So you see how much we need to do to make things backward compatible.

**Comment by HenryLeongStat** [comment]
Let me take a look with that!

But what do you mean the `old version of sos_notebook` and the `updated sos_notebook`?

**Comment by BoPeng** [comment]
We can also make the new language module depends on newer version of `sos_notebook` to avoid the problem of old sos notebook + new module. Anyway, the language info code in kernel.py is very complex and perhaps I will have to do that myself.

**Comment by BoPeng** [comment]
I have updated the features page. I will think the best way to really support the color.

**Comment by HenryLeongStat** [comment]
OK.. I thought it can be simply done by adding a `if` statement. I should take a look which the source code. It is a great opportunity to see the beauty of `class`

**Comment by BoPeng** [comment]
kernel.py is pretty difficult to understand because the kernel handling code involves many cases with available kernel (system) and kernels from the notebook... it would be easier for you to start something new (e.g. ruby support) than reading such existing code.

**Comment by HenryLeongStat** [comment]
Understand! Will do.
