### ISSUE TITLE
Redesign sos icon?

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos-notebook#50]
![image](https://user-images.githubusercontent.com/9889312/36935609-7e71578c-1ebf-11e8-8582-6dc4376ca844.png)

Icon for SoS was created by someone without any artistic taste (a.k.a, me) and does not match styles of other icons, at least in JupyterLab...

**Comment by gaow** [comment]
As a first pass, shall we try:

https://www.freelogodesign.org/index.html

(BTW the more i look at the current SoS logo the more I grow on it. Your design has this interesting characteristic)

**Comment by gaow** [comment]
![2018-03-03-09-44-32_scrot](https://user-images.githubusercontent.com/917985/36936203-7f58191c-1ec7-11e8-8a39-1c37eee16781.png)

**Comment by BoPeng** [comment]
The icon between two S in the last example looks interesting as it shows the hub nature of SoS.

**Comment by BoPeng** [comment]
The complete one could be the icon to the left of something like the bottom of the first one.

**Comment by gaow** [comment]
Sure, i was just playing around on that website. I think a horizontal one might fit more context, though. I cannot send a link for that specific icon ... but if you go to that link and search SoS under cateogory IT you'll run into it. But it might be random -- just tried again, and it is on the 20th page ...


![2018-03-03-10-15-40_scrot](https://user-images.githubusercontent.com/917985/36936496-f15bce7e-1ecb-11e8-9b36-5f3f842f2831.png)

**Comment by BoPeng** [comment]
I think we first need to find a good rectangle icon (without word SoS). Adding word SoS under or to the right of the icon with appropriate font/color seems to be easy.

Let me look for ideas for the icon.

**Comment by BoPeng** [comment]
![image](https://user-images.githubusercontent.com/9889312/36936641-91c28e42-1ecd-11e8-9330-bddd03bec484.png)
has a good flavor of scripts.

**Comment by BoPeng** [comment]
![image](https://user-images.githubusercontent.com/9889312/36936697-3cd51548-1ece-11e8-8894-1356199135b1.png)

We could potentially create our own at this style, with rectangle shaped SoS.

**Comment by BoPeng** [comment]
I have found it funny to have two Ss face to face

![image](https://user-images.githubusercontent.com/9889312/37502136-6b732252-289f-11e8-8fcc-8c5abfdcc741.png)
![image](https://user-images.githubusercontent.com/9889312/37502180-87653964-289f-11e8-8341-f06039d65310.png)
![image](https://user-images.githubusercontent.com/9889312/37502255-f44be9e2-289f-11e8-9b58-dcc46802d52d.png)
![image](https://user-images.githubusercontent.com/9889312/37502289-13bf087c-28a0-11e8-8243-ffba5a6a22d6.png)
![image](https://user-images.githubusercontent.com/9889312/37502380-652fccf0-28a0-11e8-8cce-8ad3dd1a8176.png)
![image](https://user-images.githubusercontent.com/9889312/37502424-a3c36e72-28a0-11e8-9b8e-ea6d6a70f043.png)
![image](https://user-images.githubusercontent.com/9889312/37502456-ce0de0e0-28a0-11e8-879e-2eb4be0757f4.png)
![image](https://user-images.githubusercontent.com/9889312/37502623-cbf4a590-28a1-11e8-91f5-f342773e25f6.png)
![image](https://user-images.githubusercontent.com/9889312/37502637-e149e2b6-28a1-11e8-9f3a-e6ff14bac183.png)
![image](https://user-images.githubusercontent.com/9889312/37502684-277d4b9c-28a2-11e8-9860-529674b11532.png)

**Comment by gaow** [comment]
Great arts! I like this one: 

![](https://user-images.githubusercontent.com/9889312/37502456-ce0de0e0-28a0-11e8-879e-2eb4be0757f4.png)

It has two S, and a flavor of Python. Some of the others indeed look a bit funny. If somehow the idea of communicating or blending can be reflected it would be even better -- currently it simply suggests stacking codes. 

Also ideally it should standout (be different from) other logos in both shape and color:

https://vatlab.github.io/sos-docs/#features

So the 2 "S" design is similar in idea to SAS but we cannot avoid it. Even python logo has the flavor of two S. The shapes are different though. In terms of color, green seems a bit Julia. 

BTW [your other post](https://github.com/vatlab/sos-notebook/issues/50#issuecomment-370160808) avoids resembling SAS and Python. But not as mature as your new post.

**Comment by BoPeng** [comment]
Then if we somehow squeeze in an O, we have something like

![image](https://user-images.githubusercontent.com/9889312/37502966-be1b4eb8-28a3-11e8-846b-00f8112a404c.png)
 
![image](https://user-images.githubusercontent.com/9889312/37503123-96000cc4-28a4-11e8-8018-8f6feae18447.png)

![image](https://user-images.githubusercontent.com/9889312/37503162-c23556aa-28a4-11e8-8aab-a3cd55caca5d.png)

![image](https://user-images.githubusercontent.com/9889312/37503313-cd5a2258-28a5-11e8-9f2d-4ea7030455a0.png)

and we can split the O in half with color from both sides...

**Comment by BoPeng** [comment]
The one you like can be twisted together with a helix shape, almost look like chromosome.

**Comment by BoPeng** [comment]
![image](https://user-images.githubusercontent.com/9889312/37504142-7b3fbcd0-28aa-11e8-8b62-61e0a874d904.png)


is the twisted version with Python color scheme, but the icon seems to be too "complex" or "crowded".

**Comment by gaow** [comment]
For versions with `o` in the center they look a bit to sparse ... how does it look if we add a little solid colored dot at the center of 

![](https://user-images.githubusercontent.com/9889312/37504299-656bf54e-28ab-11e8-9993-42cd8dde91e0.png)

as if the two S are pined to each other, to symbolize the `o`, and the idea of "connecting"?

**Comment by BoPeng** [comment]
I got the comment "that looks ugly" for the following

![image](https://user-images.githubusercontent.com/9889312/37504679-0bfada5e-28ae-11e8-920e-a9e739da67c0.png)

**Comment by BoPeng** [comment]
Idea from my boy

![image](https://user-images.githubusercontent.com/9889312/37505154-3be1e2be-28b1-11e8-8d59-a92076b42f80.png)

**Comment by BoPeng** [comment]
OK, Python-based workflow

![image](https://user-images.githubusercontent.com/9889312/37526643-ec9f7ec6-28fd-11e8-8937-b3b42fc3d8d4.png)

**Comment by gaow** [comment]
Well ... this last one might have copyright issues, right? But the idea of flow is good. Maybe adding arrow at the tip of those `S` shapes you guys proposed previously can convey the same idea?

> I got the comment "that looks ugly" for the following

Indeed. I was more thinking of a single dot like a pin sticking at the center where the 2 `S` crosses. But if there are arrows added to tips of the `S`s then a pin would no longer look relevant.

> Idea from my boy

This is in flavor along the lines of [this post](https://github.com/vatlab/sos-notebook/issues/50#issuecomment-370160808) -- i thought rectangle idea is worth a shot though less mature.

**Comment by BoPeng** [comment]
Then we can have a single S with a Python head, and a body formed by a workflow.

**Comment by BoPeng** [comment]
I think we are allowed to use Python logo

https://www.python.org/psf/trademarks/


## Derived Logos
* Derived logos must always be sufficiently different from the Python logos to allow the community to tell the difference. For example, if you want to create a derived logo for a local Python user group, you might be able to insert an unaltered Python logo graphic into the local group's name in a way that does not cause confusion. But confusingly similar derived logos are not allowed. This includes entwining Python logos with other logos, or connecting them together in a confusing manner. Logos that simply change the colors or fonts require permission from the PSF Trademarks Committee.
* Use of freely distributable derived logos as icons for files and executables -- Allowed if used to refer to the Python programming language. Commercial users should obtain permission before using derived logos as icons for proprietary file formats.
* Use of derived logos for user groups and conferences -- Allowed if used to refer to the Python programming language. Commercial user groups and for-profit conferences require permission from the PSF.
* Use of derived logos for freely distributed 3rd-party modules or tools -- Allowed if for the Python programming language. Use of derived logos for commercial modules and tools requires permission from the PSF.
* We recommend contacting the PSF for permission for all derived logos to avoid placing a confusing logo into wide-spread use. Contacting us is not a requirement for the specific non-commercial uses listed above, or when using freely distributable derived logos that have already been approved by the PSF. However, obtaining permission from the PSF is required in all other uses of a derived logo.

**Comment by BoPeng** [comment]
Python-style SoS. Do not really like it though.

![image](https://user-images.githubusercontent.com/9889312/37551655-e27da052-2971-11e8-9cc4-29cc73670ba6.png)

**Comment by BoPeng** [comment]
Snake-workflow, still not good.

![image](https://user-images.githubusercontent.com/9889312/37551964-20602596-2979-11e8-989b-56a844e31aa0.png)

![image](https://user-images.githubusercontent.com/9889312/37552002-34181a02-297a-11e8-919c-ea9c89610263.png)

**Comment by gaow** [comment]
This looks interesting : 

![](https://user-images.githubusercontent.com/9889312/37551680-d8e3cda4-2972-11e8-9a12-275f5f8442e9.png)

May I have the vector plot version to play with? I think a single `S` is nicer than 2 `S` so I'd perhaps try to merge the 2 `S` on this one

**Comment by BoPeng** [comment]
Single S

![image](https://user-images.githubusercontent.com/9889312/37557761-888fbb6e-29d7-11e8-8ef8-fc5541674dde.png)

**Comment by BoPeng** [comment]
I will email you the ai files.

**Comment by BoPeng** [comment]
I am almost happy with this

![image](https://user-images.githubusercontent.com/9889312/37558011-56895112-29db-11e8-8b33-b09fa0f4a8c8.png)

**Comment by gaow** [comment]
Got your AI files but I think you've drawn what I too think of, though I was only having 3 colors in mind (dotted center connecting head and tail). But I think your last one is as good as a paid professional can come up with!

**Comment by gaow** [comment]
The reason I said using less color is for the case when the icon is very small (eg 16x16) it still has good visibility. Do you think the latest one will have some issues when zooming out to very small icon?

**Comment by BoPeng** [comment]
We will have to zoom it and see.

**Comment by BoPeng** [comment]
I am trying to make the arrow uniform.

**Comment by BoPeng** [comment]
![image](https://user-images.githubusercontent.com/9889312/37559722-b412a258-29f8-11e8-8edb-75310184945e.png)

**Comment by BoPeng** [comment]
![image](https://user-images.githubusercontent.com/9889312/37560211-4d161ddc-2a02-11e8-8757-1879591710e1.png)

I think we should circle the symbol or make the icon round to make it good for jupyter.

**Comment by gaow** [comment]
Why is the ratio changed when in Jupyter? I think it got squeezed to slimmer!

**Comment by BoPeng** [comment]
Perhaps the png version was not exported correctly.

**Comment by BoPeng** [comment]
png version adjusted. Dare to compare?

https://www.dropbox.com/s/y9r7nwend8jvt3p/Screenshot%202018-03-17%2017.08.38.png?dl=0
![image](https://user-images.githubusercontent.com/9889312/37560436-00282c28-2a06-11e8-9e8c-5436b595833f.png)

**Comment by BoPeng** [comment]
Jupyter version

![image](https://user-images.githubusercontent.com/9889312/37560451-2fff7208-2a06-11e8-9ba8-eb9919fdf37c.png)

**Comment by BoPeng** [comment]
The fatter rectangle version looks good. It will be a lot of work to apply this logo to our doc, images etc. That has to be done gradually.
