### ISSUE TITLE
%get magic support in-place variable extraction

### ISSUE THREAD

**Issue by gaow** [vatlab/sos-notebook#66]
I often find myself doing something like this : 

![2018-04-24-11-20-42_scrot](https://user-images.githubusercontent.com/917985/39200436-c139bd46-47b1-11e8-807a-bd5405e3d1bb.png)

That is, to get data from R to Python I first have to make separate variables from each of them before using `%get` magic. I'm wondering:

1) can there be some short-cut to it?
2) more generally, what do you think about supporting nested objects in SoS in general? That is, for Python and R we have `dict()` vs `list()`. If for other languages there are similar implementations then we can perhaps make it happen, too? This may warrant another ticket but I am just bringing up some thoughts for now.

**Comment by BoPeng** [comment]
SoS supports nested variables but the behavior is only tested for simple items. You can create a ticket with a specific item to transfer and Henry can have a look and see what limitations we have and if it is possible to lift it.

**Comment by HenryLeongStat** [comment]
Hmm... I think `attributes()` in `R` might be able to do so. Sth like:

```
%use R
_string_to_py_dict <- NULL
for(i in c(1:length(attributes(obj))){
  _string_to_py_dict <- paste0(...)
}
```
When it comes to a complicated datatype, we even can define class in `Python`. But for a general way, we might need to think about it...
