### ISSUE TITLE
Support to recursively nested variables

### ISSUE THREAD

**Issue by gaow** [vatlab/sos-notebook#67]
Related to #66 . Here I provide a test data of intended behavior:

```python
import numpy as np
import pandas as pd
data = {'charater': 'pcarbo', 
        'integer1': 1, 'integer2': np.uint8(1), 
        'double1': 1.0, 'double2': np.float16(1.0), 
        'vector1': [1,2,'gaow'], 'vector2': [1,2,3], 'vector3': np.array([1,2,3]),
        'matrix': np.matrix([[1,2],[3,4]]),
        'array1': np.array([[1,2],[3,4]]), 'array2': [[1,2],[3,4]],
        'dataframe': pd.DataFrame({'A': [1,2], 'B': [3,4]}, index=['row1', 'row2'])
       }
data['recursive'] = data
```

@HenryLeongStat  At least for now when  I try to get it from R it crashes my notebook. So we'll be counting on your magic :)

**Comment by BoPeng** [comment]
![image](https://user-images.githubusercontent.com/9889312/39203483-892153ca-47ba-11e8-9856-e341b6b516b3.png)

**Comment by gaow** [comment]
It is like:

```
> v=2
> v=list(v=v)
> v
$v
[1] 2
```

In my example in #66 as you probably can tell I did not capture the part that defines variable `res` but it is basically of the same nature.

**Comment by BoPeng** [comment]
The two `v`s are different and your `v$v` is not a list. But the following is possible:

![image](https://user-images.githubusercontent.com/9889312/39203544-b1fc1ee2-47ba-11e8-947f-eb3320caf679.png)

**Comment by gaow** [comment]
Oh sure, one can nest many levels:

```r

> v=2
> v=list(v=v)
> v
$v
[1] 2

> v=list(v=v)
> v
$v
$v$v
[1] 2


> v=list(v=v)
> v
$v
$v$v
$v$v$v
[1] 2
```

**Comment by BoPeng** [comment]
It can be really tricky to detect nested items. There are two possibilities,

In [`_R_repr(obj)`](https://github.com/vatlab/sos-r/blob/master/src/sos_r/kernel.py#L46), record converted `obj` and raise an error (or return a dummy string) when an object is converted more than once. Something like

```
converted_objs = set()
_R_repr(obj):
    if obj in coverted_objs:
        return 'NULL"
    else:
        converted_objs.add(obj)
    ....
```
Or we could allow some nesting and do something like

```
_R_repr(obj, nested=0):
    ....
    if nested == 10:
        return 'null'
    ....
    _R_repr(something, nested + 1)
```

**Comment by HenryLeongStat** [comment]
For @gaow 's example, data['recursive'] seems "infinite" recursive. 
But in `R`, by doing v=list(v=v) every time, it will just increase one level of nest...

**Comment by HenryLeongStat** [comment]
How about a named vector in R?

```
v=NA
names(v) <- v
> v
<NA> 
  NA
> v[v]
<NA> 
  NA 
> v[v][v]
<NA> 
  NA 
> v[v][v][v]
<NA> 
  NA 
```

**Comment by HenryLeongStat** [comment]
In Python:
```
data={}
data['recursive']=data
data['recursive']
Out[52]: {'recursive': {...}}
data['recursive']['recursive']
Out[53]: {'recursive': {...}}
data['recursive']['recursive']['recursive']
Out[54]: {'recursive': {...}}
```

**Comment by HenryLeongStat** [comment]
`Named vector` works for 1 dimension case:
```
> v <- c(1,2,3,4,5)
> v
[1] 1 2 3 4 5
> v[v]
[1] 1 2 3 4 5
> v[v][v]
[1] 1 2 3 4 5
```

But it fails for the case with higher dimension (of course, it called "vector"...):
```
> v <- diag(1,3)
> v
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    1    0
[3,]    0    0    1
> v[v]
[1] 1 1 1
> v[v][v]
[1] 1 1 1
```

**Comment by HenryLeongStat** [comment]
@BoPeng Professor, do you think it is possible for us to design a class in R for this situation?

**Comment by HenryLeongStat** [comment]
For the simple case, SoS won't crash:
<img width="999" alt="screen shot 2018-04-30 at 1 56 03 pm" src="https://user-images.githubusercontent.com/26916551/39444706-3eb7ca80-4c7e-11e8-8d8c-12e37afe3c50.png">

Let me find out what causes SoS crashing.

**Comment by BoPeng** [comment]
What class? We are talking about two ways, python to R and R to python here.

**Comment by HenryLeongStat** [comment]
I know. I mean:
For `Python` to `R`, if the recursive variable is one dimension, we can use `named vector` in R to get it, and vice versa. (one dimension  `Python` `recursive variable` to get `R` `named vector`)

For `R` to `Python` to , if the recursive variable is one dimension, we can use `named vector` in R to get it, and vice versa. (one dimension  `Python` `recursive variable` to get `R` `named vector`)

**Comment by HenryLeongStat** [comment]
OK! For detecting, we can simply do:
```
for key in data:
    if data[key] == data:
        "The variable is recursive"
        break
        ....
```

But for the one-dimension recursive variable, it's easy to do the lossless conversion.

**Comment by BoPeng** [comment]
I think we can just keep tracked of converted objects, with the idea above

```
converted_objs = set()
_R_repr(obj):
    if obj in coverted_objs:
        return 'NULL"
    else:
        converted_objs.add(obj)
    ....
```

**Comment by BoPeng** [comment]
Here `converted_objs` can store the `id(obj)` of the object because `id()` of an object is "an integer which is guaranteed to be unique and constant for this object during its lifetime"

**Comment by HenryLeongStat** [comment]
Not quite understand 
```
converted_objs = set()
_R_repr(obj):
    if obj in coverted_objs:
        return 'NULL"
    else:
        converted_objs.add(obj)
    ....
```

Do you mean:
```
v = {}
v['recursive'] = v
# ????
converted_objs = set(v)
_R_repr(obj):
    # obj is v
    if obj in coverted_objs:
        return 'NULL"
    else:
        converted_objs.add(obj)
    ....
```

**Comment by BoPeng** [comment]
I mean, when we try to get the R expression of the python object, we are doing `_R_repr(obj)`, then, during this process, we have

1. `_R_repr(obj)` ==> `converted_objs = {id(obj)}`
2. `_R_repr(v['recursive'])` ==> `v['recursive']` already in `converted_objs` so we return `NULL` and do not trace into `v['recursive']` which is actually `v`.

**Comment by HenryLeongStat** [comment]
Understood! So it will prevent the infinite loop which causes SoS crashes.

**Comment by gaow** [comment]
Okay I've got this perhaps corner case today, possibly related to fixes for this ticket:

![2018-05-03-11-16-07_scrot](https://user-images.githubusercontent.com/917985/39589334-80b6dda8-4ec3-11e8-884d-2f7ec0a0c589.png)

**Comment by BoPeng** [comment]
Well, bad memory here, sign of getting old or lack of sleep or both. The magic was designed to save a cell-level workflow to a .sos file but all my workflows are large and multi-cell and are saved with `%sossave`. I suppose this is the equivalence of `%run` magic to `%sosrun`.

**Comment by BoPeng** [comment]
Indeed a bug caused by the use of `%save` in non-SoS cells, not related to this ticket though. Try again please.

**Comment by HenryLeongStat** [comment]
https://github.com/vatlab/sos-r/commit/6ce7cd1d7c2d29266575b96d1f76842c5d272b09

For now it only prevents SoS crashing. But still, I think for the 1 dimension case, we can do something for it!

**Comment by gaow** [comment]
@HenryLeongStat @BoPeng I was most interested in the recursive loading function of `reticulate` package. I took the example here, saved it to `pickle` format,

```python
import pickle
pickle.dump(data, open('test.pkl', 'wb'))
```

and load it in R:

```r
data = reticulate::py_load_object('test.pkl')
```

It freezes. But if I change the `recursive` line to

```python
from copy import deepcopy
data['recursive'] = deepcopy(data)
```

then load it in R, I got it work! The outcome is reasonable, see end of the threads.

Also it is reasonably fast. If you run it first time it is a bit slow because I assume it loads packages to it. But the 2nd time it is a lot faster, within a fraction of seconds.

it's something isn't it?

## outcome of the code above
```r
$charater
[1] "pcarbo"

$integer1
[1] 1

$integer2
[1] 1

$double1
[1] 1

$double2
[1] 1

$vector1
$vector1[[1]]
[1] 1

$vector1[[2]]
[1] 2

$vector1[[3]]
[1] "gaow"


$vector2
[1] 1 2 3

$vector3
[1] 1 2 3

$matrix
     [,1] [,2]
[1,]    1    2
[2,]    3    4

$array1
     [,1] [,2]
[1,]    1    2
[2,]    3    4

$array2
$array2[[1]]
[1] 1 2

$array2[[2]]
[1] 3 4


$dataframe
      A  B
row1  1  3
row2  2  4

$recursive
$recursive$charater
[1] "pcarbo"

$recursive$integer1
[1] 1

$recursive$integer2
[1] 1

$recursive$double1
[1] 1

$recursive$double2
[1] 1

$recursive$vector1
$recursive$vector1[[1]]
[1] 1

$recursive$vector1[[2]]
[1] 2

$recursive$vector1[[3]]
[1] "gaow"


$recursive$vector2
[1] 1 2 3

$recursive$vector3
[1] 1 2 3

$recursive$matrix
     [,1] [,2]
[1,]    1    2
[2,]    3    4

$recursive$array1
     [,1] [,2]
[1,]    1    2
[2,]    3    4

$recursive$array2
$recursive$array2[[1]]
[1] 1 2

$recursive$array2[[2]]
[1] 3 4


$recursive$dataframe
      A  B
row1  1  3
row2  2  4
```

**Comment by BoPeng** [comment]
Why cannot we just use reticulate to load complex data type?

**Comment by BoPeng** [comment]
Note that your use of 

```
from copy import deepcopy
data['recursive'] = deepcopy(data)
```
essentially makes the data non-recursive. So reticulate does not handle recursive either.

**Comment by gaow** [comment]
No it does not. I was just commenting that reticulate seems to be doing a good job reading Python objects to R -- if we have evaluated reticulate earlier it might save us some efforts writing our own code for it.

**Comment by BoPeng** [comment]
We should only use `reticulate` for datatypes we cannot handle because using pickle is slow for small datatypes and way too slow for large dataframes.

There is also the dependency issue if we depend on it... we 

1. cannot put it inside `pip install sos-r` because side effect is not recommended
2. cannot install it automatically when the kernel loads because in theory users might not have internet access

so we have to list it in installation instruction.

**Comment by BoPeng** [comment]
Nested variable is set to `NULL` directly.
