### ISSUE TITLE
`master` broken?

### ISSUE THREAD

**Issue by gaow** [vatlab/sos-notebook#69]
See the error message below:

![2018-04-30-17-28-52_scrot](https://user-images.githubusercontent.com/917985/39453613-41d390a0-4c9c-11e8-98a5-71fd929af582.png)

I'm sure it is legitimate syntax before.

**Comment by BoPeng** [comment]
%run only applies to current cell

**Comment by BoPeng** [comment]
OK, now I recall this feature, and is documented at [here](https://vatlab.github.io/sos-docs/doc/documentation/Notebook_Interface.html#Magic_run).

This part of code was rewritten in coordinance with the jupyterlab extension and I must have removed it accidentally.

**Comment by gaow** [comment]
Good to hear! I don't think I know about the documentation but I know that my life depends on it :)

**Comment by BoPeng** [comment]
Note that our current test mechanism cannot test multi-cell operations so I cannot add this to our test suite.
