### ISSUE TITLE
Support for ArcGIS

### ISSUE THREAD

**Issue by HenryLeongStat** [vatlab/sos-notebook#70]
Had a meeting with two leads this morning. I introduced them `SoS` and they seemed quite interested in it! 😄 I am helping them to write a proposal to install Jupyter Notebook and `SoS` in our "protected" system.

Since there are some GIS guys in my team and the other team, they wanted to install ArcGIS kernel as well. I am wondering if it is possible to support ArcGIS in SoS? I talked with the GIS team director and he said there are plenty of datatypes in ArcGIS. Even if not all the datatypes, maybe we can support some of them?

**Comment by BoPeng** [comment]
Sure we can make SoS work with ArcGIS as long as you can contribute a language module. It sounds like your work would be recognized by your team as well (so forget about ruby for a while).

**Comment by HenryLeongStat** [comment]
>ArcGIS seems to be using Python in Jupyter, so all you need to do is to add the kernel name to the supported list of the sos-python module here and add the language here. Please try and let me know if it works for you.

OK! Will do!!

**Comment by BoPeng** [comment]
Sorry, spoke too fast. ArcGIS uses python3 kernel so you do not have do anything at all....

**Comment by HenryLeongStat** [comment]
>Sorry, spoke too fast. ArcGIS uses python3 kernel so you do not have do anything at all....

Not sure python 3 is available, but the GIS expert at my team uses python 2. 
(https://support.esri.com/en/technical-article/000013224)

**Comment by BoPeng** [comment]
It does not matter. If it uses python 2, you will have to install python2 to support ArcGIS anyway, and SoS works with Python2.

**Comment by HenryLeongStat** [comment]
OK! Never use ArcGIS, but I will test it out.
