### ISSUE TITLE
Syntax highlighting sometimes not shown when notebook opens.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos-notebook#73]
For some unknown reason, some notebooks do not show syntax highlighting when it opens. Clicking individual cells will show syntax highlighting, refreshing the page might also work. This might be caused by slow server that fails to process the highlighting code in time (so the browser just stops it).

**Comment by gaow** [comment]
I get this too and made peace with it. But jupyter-sos doesn't have the
problem.

Sent from handheld. Sorry for poor text.

**Comment by BoPeng** [comment]
I think the problem is with [this kernel ready event](https://github.com/vatlab/sos-notebook/blob/master/src/sos_notebook/kernel.js#L2070). Basically I am trying to apply syntax highlighting when the kernel is connected but if the document is long or if the server is slow, the js code cannot be completed in a "short time" defined by Chrome and would be stopped.

The trick should be a chain of promise actions that highlight cells one by one.

**Comment by BoPeng** [comment]
Please test and let me know if the problem persists. The problem with Jupyter is that it does not really support per-cell highlighting so it would broadcast a mode (e.g. `sos`) and `sos-notebook` would have to override its mode at times. JupyterLab does not have this problem because I was able to make sure things work optimally with a PR. :smile:

**Comment by gaow** [comment]
Great -- for my relatively long notebook, it didn't show instantly, but it kicked in after a couple of seconds.

**Comment by BoPeng** [comment]
Good. That is the whole point. The browser would kill the highlighting code if it takes longer than a few ms to execute so now sos highlight a cell, wait 0.1s and move to the next one. The 0.1s can be reduced even to 0s, I guess, because the browser would not complain as long as each piece is completed quickly.
