### ISSUE TITLE
A %revisions magic to show revisions from a repository

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos-notebook#74]
Something like what the following (a screenshot from workflowr). It can be difficult to do this from a web environment because the frontend in theory does not touch host file system. The kernel can somehow call `git log` and parse its output though.

![2018-05-10-09-15-26_scrot](https://user-images.githubusercontent.com/917985/39874308-0bd9723c-5433-11e8-96cc-a89cbb1ad22d.png)

**Comment by gaow** [comment]
This would be a great feature to have -- very appealing.

I think it would be even better to do this:

```
%revisions --source https://github.com/stephenslab/gtexresults/blob/{revision}/analysis/Fig.Uk3.Rmd --html https://cdn.rawgit.com/stephenslab/gtexresults/{revision}/docs/Fig.Uk3.html
```

then under the hood, the output would look like:

|  Revision  |  Version |  Author  |   Date |   Message |
|---|---|---|---|---|
|   18 |  80f285fa [[source](https://github.com/stephenslab/gtexresults/blob/80f285faf2eaf3c1e1b4fc25317c58996d5b2525/analysis/Fig.Uk3.Rmd)/[html](https://cdn.rawgit.com/stephenslab/gtexresults/80f285faf2eaf3c1e1b4fc25317c58996d5b2525/docs/Fig.Uk3.html)] | Gao Wang  | 2017-05-30  |Update figures   |
|   |   |   |   |   |

That is a easy way to mimic what workflowr does, and is more compact (consolidating source and HTML) and flexible (we can support via this type of template not just github links).

**Comment by BoPeng** [comment]
We should be able to figure out source automatically through the `git remote show origin`, right? `html` is another story because it points to another file.

**Comment by gaow** [comment]
Sure, but that requires password for private repo unless some ssh token is set. Also it does not expand the rest of the URL which might have different convention in different hosting services I suspect. I think it is good enough to use some solution that requires explicit specification like that in order for hyper-links to show up. One only has to do this once per notebook and will never have to worry about keeping different versions of the notebook because it is so easy to track it back. That should make implementation easier?

**Comment by BoPeng** [comment]
Implemented and documented [here](https://vatlab.github.io/sos-docs/doc/documentation/SoS_Magics.html#magic_revisions). Let me know if you have any comment.

**Comment by gaow** [comment]
Oh it looks fantastic! Perhaps only one thing for now: can we add a toggle one way or another? A notebook maybe revised many times. Without a toggling I'd put this table at the end of a notebook where I have `%sessioninfo`, which is a bit messy. A toggle would be good.

**Comment by gaow** [comment]
Sorry, I just noticed `-n` option. So with `-n` it is better, I guess.

**Comment by BoPeng** [comment]
Yes, there is a huge amount of options for `git log` and you can pick which revisions to display. I though of  a default `-n 10` but decide not to change the default behavior of `git log`.

**Comment by BoPeng** [comment]
@gaow What is the link for workflowr with revisions of figures? I recently found nbdime which can achieve similar effect and I would like to propose the workflowr diff format for it.

**Comment by gaow** [comment]
@BoPeng Are you asking about an example? Here is one:

https://stephenslab.github.io/gtexresults/Uk3.html

Please let me know if it is what you need!

**Comment by BoPeng** [comment]
I am looking for an example with some thing that expands previous version of figure.

**Comment by gaow** [comment]
Yes that link should demonstrate it.
