### ISSUE TITLE
Default language cell

### ISSUE THREAD

**Issue by luluperet** [vatlab/sos-notebook#81]
it's possible to have a default language for the cells ? (sometimes it's blank)
it's possible when we create a cell that it have as default language the previous set language ?

**Comment by BoPeng** [comment]
Did you try the global language selector in the toolbar?

**Comment by luluperet** [comment]
yes, but that stay blank
<img width="1045" alt="capture d ecran 2018-05-28 a 01 43 56" src="https://user-images.githubusercontent.com/15991202/40591886-e6e70702-6218-11e8-94f9-13ebd195d43f.png">
<img width="1061" alt="capture d ecran 2018-05-28 a 01 44 04" src="https://user-images.githubusercontent.com/15991202/40591887-e6fd96fc-6218-11e8-9034-9d100182a937.png">

**Comment by BoPeng** [comment]
"blank" means "default" and cells with blank language will be realized to the global default when the cell is executed. Changing global default will not change the appearance of existing cells with either assigned or "blank" language although the underlying language will be changed for the latter.

It is of course possible to set new cells to global default but the question is whether or not we should change the language of "new" cells with the change of global default, and what constitute "new" cells if we decide to change. I could not decide which way is better and thought that a "default"/"blank" status is most intuitive.

**Comment by BoPeng** [comment]
@gaow What do you think about this behavior? Would the following be more intuitive?

1. New cells immediately marked with global default
2. Change of global default does not affect any existing cell (new or not)

Basically users will have to use cell-level selector for existing cells, change of global default will affect new cells only.

**Comment by gaow** [comment]
@BoPeng in fact if you try the JupyerLab SoS, the behavior is currently what you have proposed ... So maybe we make it the same in SoS Notebook?

**Comment by BoPeng** [comment]
I did not "propose" it because I sort of like the side effect of having new cells having the current global default. I was however sometimes surprised to have a cell evaluated in R when the cell does not have a gray prompt (when I set the default to R) so having a "default" changing language might not be very good.

**Comment by BoPeng** [comment]
Now I remember at least one of the scenarios for a "blank" cell language. That is to say, when you switch the kernel of a non-SoS (e.g. R) notebook to SoS. With the old behavior, you simply change the global default to R, and you can run the notebook without problem. With the new behavior, you will have to change the language of cells one by one to R.

**Comment by gaow** [comment]
Okay, I can appreciate the motivation to keep the default side-effect of SoS Notebook behavior, but I do think it is perhaps not that common to switch kernel for an established notebook. So the current behavior should be more intuitive and consistent with SoS JupytherLab.

**Comment by BoPeng** [comment]
A minor problem with the language-switching mechanism is that once you switch a cell to markdown and back, it will always be the global default kernel (not necessarily SoS) because markdown cells do not have meta data so the kernel information is lost during the conversion.

Other than that the new behavior is working as expected. Closing the ticket now.
