### ISSUE TITLE
how to add R kernel to SoS notebook?

### ISSUE THREAD

**Issue by vibbits** [vatlab/sos-notebook#85]
Hello
I am using the SoS and load a file but when I want to switch kernel between kernel in the drop-down menu I can only select between SoS, SAS or Python3. I wonder how do I add R to the selection of kernels? 
Thank you! Oren

**Comment by BoPeng** [comment]
There are basic troubleshooting steps after "supported languages" at [Running SoS page](https://vatlab.github.io/sos-docs/#runningsos). Basically you need to check if R can be used in Jupyter, and see if `sos-r` is properly installed. Note that `sos-r` is now listed as dependency of `sos-notebook` so you do not have to install it separately, but a notorious problem is that if you installed these modules through `pip` and `python setup.py`, then you can end up with two versions locally and have to remove `site-packages/sos_r*` and re-install.

**Comment by BoPeng** [comment]
Oh, if you do not even see `ir` in the dropdown list, the R kernel is not installed properly. Check the `R` section under https://vatlab.github.io/sos-docs/#runningsos for details.

**Comment by BoPeng** [comment]
I assume that the problem has been resolved.

**Comment by wangbinhu** [comment]
@BoPeng big god, can you say detail bash commands of  install  R kernel ?,thank you!

**Comment by BoPeng** [comment]
Did you check out the R section in https://vatlab.github.io/sos-docs/running.html#content ? Basically, the most difficult part is to get irkernel working and you should consult the irkernel documentation to install it.. The rest of the step concerning SoS is trivial.

**Comment by wangbinhu** [comment]
@BoPeng tank you , problme has solved.
