### ISSUE TITLE
Use codemirror instead of pygments for sos reports.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos-notebook#87]
Right now sos uses `jupyter convert` to convert notebooks to HTML, which uses pygments to highlight source code. The Lexer we are using is  a simple extension of python lexer and is not as powerful as our code mirror mode. It is possible that we customize our template to use code mirror to highlight cell inputs, which will produce more consistent output although the HTML files will not be viewable without network connection (because the need to download codemirror js code from online).

**Comment by BoPeng** [comment]
Working now. I even added a language selector so the documentation now looks almost identical to live notebook.

**Comment by gaow** [comment]
It does not work for me:

```
sos convert  Process_Oriented.sos Process_Oriented.html --style 'solarized light' --lineno
```

and I get:

![2018-06-12-15-55-26_scrot](https://user-images.githubusercontent.com/917985/41316840-0fd71552-6e59-11e8-8001-d56c8157493e.png)

**Comment by BoPeng** [comment]
Not sure why it was not pushed in.... Try again now. Note that the styles are now codemirror themes, not pygment styles, use `sos convert sos-html -h` to get a list of themes. Also, `--linenos` is now deprecated and line number is always on.

**Comment by BoPeng** [comment]
Just to keep a note that `sos convert sos html` embed a copy of `sos-mode.js` so that it can be displayed properly even if the sos website is down. Our online documentation uses the online version
```
      <script src="https://vatlab.github.io/sos-docs/js/sos-mode.js"></script>
```
because they are online anyway. The converted HTML would be a lot smaller if we use `css` and `js` files from `sos-docs` though.
