### ISSUE TITLE
Trouble in viewing ipynb files.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos-notebook#88]
I have lot of analysis done in SoS saved in ipynb formats. Whenever I need to view them, I will have to start a Jupyter notebook server and open the files there, which is a lot of work. 

Given that we now how a conversion mechanism (using codemirror) that can render the notebooks in their original format, it would be helpful for us to provide some way to show the ipynb report easier. Something like a shortcut to

```
sos convert my.ipynb /tmp/temp.html --template a_doc_template_with_toc
open /tmp/temp.html
```

It could be something like

```
sos convert my.ipynb --to-html --view
```
or even simpler
```
sos view my.ipynb
```

**Comment by BoPeng** [comment]
Note that currently we have
```
sos convert my.sos --to-html --view
```
which converts sos to a temporary html file and view it.

**Comment by BoPeng** [comment]
OK, now that

```
sos convert my.ipynb --to-html --view
```
works, the question is whether or not we should provide a shortcut for it.

There are several possibilities:

1. User use 
```
alias  sosview='sos convert $1 --to html --view'
```

2. We provide a dedicated command `sos-viewer` so that users can register it with file browser and user can double click and use `sos-viewer` to open ipynb file (and possibly also sos file). Under windows, we could even register the command during installation.

3. We provide a subcommand ```sos view```

**Comment by HenryLeongStat** [comment]
That seems quite convenient! Is it all done in commandline?

Is the html file saved in `tmp`? Or we can choose the name and save it to anywhere?

**Comment by BoPeng** [comment]
You can choose a name and use command such as

```
sos convert my.ipynb my.html --view
```
while `--view` is optional.

It uses a default template without all the fancy codemirror syntax highlighting so I might add a template later.

**Comment by BoPeng** [comment]
The `--to html` option was used to view a temporary file and avoid saving to a perminant HTML file.

**Comment by HenryLeongStat** [comment]
That's nice! With that, I can show all my work to the non-jupyter users! 

Are there any other things that `sos convert` can do? Or it is designed for this particular function? If the later, I will vote for `sos view`, since it's easy to remember :D. But maybe `sos convert` is more clear in case users want to save the html not in `tmp`?

**Comment by BoPeng** [comment]
`sos convert -h` will show you a list of options.

**Comment by HenryLeongStat** [comment]
I see. So we need to use `sos convert my.ipynb --to-html` to call the converter, `ipynb-html`.

I think it is quite clear.

**Comment by BoPeng** [comment]
Need to note that `jupyter notebook file.ipynb` can start a jupyter server and open `file.ipynb`.
